package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// BandaraList is the resolver for the bandaraList field.
func (r *queryResolver) BandaraList(ctx context.Context) ([]*model.Bandara, error) {
	list := r.bandaraSvc.GetAll()
	result := make([]*model.Bandara, len(list))
	for i, item := range list {
		item := item
		result[i] = &model.Bandara{
			KodeIata: item.KodeIATA,
			Nama:     item.Nama,
			Kota:     item.Kota,
			Provinsi: item.Provinsi,
		}
	}
	return result, nil
}

// BandaraDetail is the resolver for the bandaraDetail field.
func (r *queryResolver) BandaraDetail(ctx context.Context, kode string) (*model.Bandara, error) {
	item := r.bandaraSvc.GetByKode(kode)
	if item == nil {
		return nil, nil
	}
	return &model.Bandara{
		KodeIata: item.KodeIATA,
		Nama:     item.Nama,
		Kota:     item.Kota,
		Provinsi: item.Provinsi,
	}, nil
}
