package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// IuranBpjs is the resolver for the iuranBPJS field.
func (r *queryResolver) IuranBpjs(ctx context.Context) ([]*model.IuranBpjs, error) {
	list := r.bpjsSvc.GetIuran()
	result := make([]*model.IuranBpjs, len(list))
	for i, item := range list {
		item := item
		result[i] = &model.IuranBpjs{
			Kelas:      item.Kelas,
			Segmen:     item.Segmen,
			Nominal:    item.Nominal,
			Keterangan: item.Keterangan,
		}
	}
	return result, nil
}
