package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// BudayaDaerahList is the resolver for the budayaDaerahList field.
func (r *queryResolver) BudayaDaerahList(ctx context.Context) ([]*model.BudayaDaerah, error) {
	list := r.budayaDaerahSvc.ListAll(ctx)
	result := make([]*model.BudayaDaerah, len(list))
	for i, b := range list {
		b := b
		result[i] = &model.BudayaDaerah{
			Provinsi:    b.Provinsi,
			RumahAdat:   b.RumahAdat,
			PakaianAdat: b.PakaianAdat,
			TariDaerah:  b.TariDaerah,
		}
	}
	return result, nil
}

// BudayaDaerahCari is the resolver for the budayaDaerahCari field.
func (r *queryResolver) BudayaDaerahCari(ctx context.Context, provinsi string) ([]*model.BudayaDaerah, error) {
	list := r.budayaDaerahSvc.Cari(ctx, provinsi)
	result := make([]*model.BudayaDaerah, len(list))
	for i, b := range list {
		b := b
		result[i] = &model.BudayaDaerah{
			Provinsi:    b.Provinsi,
			RumahAdat:   b.RumahAdat,
			PakaianAdat: b.PakaianAdat,
			TariDaerah:  b.TariDaerah,
		}
	}
	return result, nil
}
