package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// Cuaca is the resolver for the cuaca field.
func (r *queryResolver) Cuaca(ctx context.Context, provinsiKode string, kota string) (*model.CuacaResult, error) {
	res, err := r.cuacaSvc.GetCuaca(ctx, provinsiKode, kota)
	if err != nil {
		return nil, err
	}
	prakiraans := make([]*model.Prakiraan, len(res.Prakiraan))
	for i, p := range res.Prakiraan {
		prakiraans[i] = &model.Prakiraan{
			Waktu:          p.Waktu,
			Suhu:           p.Suhu,
			Kelembapan:     p.Kelembapan,
			Cuaca:          p.Cuaca,
			KecepatanAngin: p.KecepatanAngin,
			ArahAngin:      p.ArahAngin,
		}
	}
	return &model.CuacaResult{
		Provinsi:  res.Provinsi,
		Kota:      res.Kota,
		Prakiraan: prakiraans,
	}, nil
}
