package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// HargaEmas is the resolver for the hargaEmas field.
func (r *queryResolver) HargaEmas(ctx context.Context) ([]*model.HargaEmasItem, error) {
	list, err := r.elasSvc.GetAll()
	if err != nil {
		return nil, err
	}
	result := make([]*model.HargaEmasItem, len(list))
	for i, item := range list {
		item := item
		result[i] = &model.HargaEmasItem{
			Gram:         item.Gram,
			HargaJual:    item.HargaJual,
			HargaBuyback: item.HargaBuyback,
		}
	}
	return result, nil
}
