package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// GempaTerbaru is the resolver for the gempaTerbaru field.
func (r *queryResolver) GempaTerbaru(ctx context.Context) (*model.GempaItem, error) {
	item, err := r.gempaSvc.GetTerbaru()
	if err != nil {
		return nil, err
	}
	return &model.GempaItem{
		Tanggal:   item.Tanggal,
		Jam:       item.Jam,
		Magnitude: item.Magnitude,
		Kedalaman: item.Kedalaman,
		Lintang:   item.Lintang,
		Bujur:     item.Bujur,
		Wilayah:   item.Wilayah,
		Potensi:   item.Potensi,
		Dirasakan: item.Dirasakan,
	}, nil
}

// GempaList is the resolver for the gempaList field.
func (r *queryResolver) GempaList(ctx context.Context) ([]*model.GempaItem, error) {
	list, err := r.gempaSvc.GetList()
	if err != nil {
		return nil, err
	}
	result := make([]*model.GempaItem, len(list))
	for i, item := range list {
		item := item
		result[i] = &model.GempaItem{
			Tanggal:   item.Tanggal,
			Jam:       item.Jam,
			Magnitude: item.Magnitude,
			Kedalaman: item.Kedalaman,
			Lintang:   item.Lintang,
			Bujur:     item.Bujur,
			Wilayah:   item.Wilayah,
			Potensi:   item.Potensi,
			Dirasakan: item.Dirasakan,
		}
	}
	return result, nil
}
