package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// GunungBerapiList is the resolver for the gunungBerapiList field.
func (r *queryResolver) GunungBerapiList(ctx context.Context) ([]*model.GunungBerapi, error) {
	list := r.gunungBerapiSvc.ListAll(ctx)
	result := make([]*model.GunungBerapi, len(list))
	for i, g := range list {
		g := g
		result[i] = &model.GunungBerapi{
			Nama:                    g.Nama,
			Bentuk:                  g.Bentuk,
			TinggiMeter:             g.TinggiMeter,
			EstimasiLetusanTerakhir: g.EstimasiLetusanTerakhir,
			Geolokasi:               g.Geolokasi,
		}
	}
	return result, nil
}

// GunungBerapiCari is the resolver for the gunungBerapiCari field.
func (r *queryResolver) GunungBerapiCari(ctx context.Context, nama string) ([]*model.GunungBerapi, error) {
	list := r.gunungBerapiSvc.Cari(ctx, nama)
	result := make([]*model.GunungBerapi, len(list))
	for i, g := range list {
		g := g
		result[i] = &model.GunungBerapi{
			Nama:                    g.Nama,
			Bentuk:                  g.Bentuk,
			TinggiMeter:             g.TinggiMeter,
			EstimasiLetusanTerakhir: g.EstimasiLetusanTerakhir,
			Geolokasi:               g.Geolokasi,
		}
	}
	return result, nil
}
