package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/internal/domain"
)

// Tanggal is the resolver for the tanggal field.
func (r *hariLiburResolver) Tanggal(ctx context.Context, obj *domain.HariLibur) (string, error) {
	return obj.Tanggal.Format("2006-01-02"), nil
}

// HariLibur is the resolver for the hariLibur field.
func (r *queryResolver) HariLibur(ctx context.Context, tahun int, bulan *int) ([]*domain.HariLibur, error) {
	var items []domain.HariLibur
	var err error
	if bulan != nil {
		items, err = r.hariLiburSvc.ListByBulan(ctx, tahun, *bulan)
	} else {
		items, err = r.hariLiburSvc.ListByTahun(ctx, tahun)
	}
	if err != nil {
		return nil, err
	}
	out := make([]*domain.HariLibur, len(items))
	for i := range items {
		out[i] = &items[i]
	}
	return out, nil
}

// HariLiburHariIni is the resolver for the hariLiburHariIni field.
func (r *queryResolver) HariLiburHariIni(ctx context.Context) (*domain.HariLibur, error) {
	return r.hariLiburSvc.GetHariIni(ctx)
}

// HariLibur returns HariLiburResolver implementation.
func (r *Resolver) HariLibur() HariLiburResolver { return &hariLiburResolver{r} }

type hariLiburResolver struct{ *Resolver }
