package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// Ihsg is the resolver for the ihsg field.
func (r *queryResolver) Ihsg(ctx context.Context) (*model.IHSGResult, error) {
	res, err := r.ihsgSvc.GetIHSG()
	if err != nil {
		return nil, err
	}
	return &model.IHSGResult{
		Symbol:              res.Symbol,
		Nama:                res.Nama,
		Harga:               res.Harga,
		Perubahan:           res.Perubahan,
		PersentasePerubahan: res.PersentasePerubahan,
		Open:                res.Open,
		High:                res.High,
		Low:                 res.Low,
		Volume:              res.Volume,
		Waktu:               res.Waktu,
	}, nil
}

// Saham is the resolver for the saham field.
func (r *queryResolver) Saham(ctx context.Context, kode string) (*model.SahamResult, error) {
	res, err := r.ihsgSvc.GetSaham(kode)
	if err != nil {
		return nil, err
	}
	return &model.SahamResult{
		Symbol:              res.Symbol,
		Nama:                res.Nama,
		Harga:               res.Harga,
		Perubahan:           res.Perubahan,
		PersentasePerubahan: res.PersentasePerubahan,
		Open:                res.Open,
		High:                res.High,
		Low:                 res.Low,
		Volume:              res.Volume,
		Waktu:               res.Waktu,
	}, nil
}
