package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// Inflasi is the resolver for the inflasi field.
func (r *queryResolver) Inflasi(ctx context.Context, tahun *int) ([]*model.InflasiItem, error) {
	list := r.inflasiSvc.GetAll(tahun)
	result := make([]*model.InflasiItem, len(list))
	for i, item := range list {
		item := item
		result[i] = &model.InflasiItem{
			Periode:        item.Periode,
			Bulan:          item.Bulan,
			Tahun:          item.Tahun,
			InflasiBulanan: item.InflasiBulanan,
			InflasiTahunan: item.InflasiTahunan,
			Ihk:            item.IHK,
		}
	}
	return result, nil
}
