package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// KalenderHijriyah is the resolver for the kalenderHijriyah field.
func (r *queryResolver) KalenderHijriyah(ctx context.Context, tanggal string) (*model.KalenderHijriyahResult, error) {
	res, err := r.kalenderHijriyahSvc.Convert(tanggal)
	if err != nil {
		return nil, err
	}
	return &model.KalenderHijriyahResult{
		TanggalMasehi:   res.TanggalMasehi,
		TanggalHijriyah: res.TanggalHijriyah,
		Hari:            res.Hari,
		HariArab:        res.HariArab,
		Bulan:           res.Bulan,
		BulanArab:       res.BulanArab,
		Tahun:           res.Tahun,
	}, nil
}
