package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
	"github.com/lisvindanuu/indonesiaql/internal/service"
)

// KalenderJawa is the resolver for the kalenderJawa field.
func (r *queryResolver) KalenderJawa(ctx context.Context, tanggal string) (*model.KalenderJawaResult, error) {
	res, err := service.KalenderJawa(tanggal)
	if err != nil {
		return nil, err
	}
	return &model.KalenderJawaResult{
		TanggalMasehi:   res.TanggalMasehi,
		Hari:            res.Hari,
		Pasaran:         res.Pasaran,
		Wuku:            res.Wuku,
		TahunJawa:       res.TahunJawa,
		NamaWindu:       res.NamaWindu,
		TahunDalamWindu: res.TahunDalamWindu,
	}, nil
}
