package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// KodePos is the resolver for the kodePos field.
func (r *queryResolver) KodePos(ctx context.Context, kode string) ([]*model.KodePosResult, error) {
	list, err := r.kodePosSvc.Search(ctx, kode)
	if err != nil {
		return nil, err
	}
	result := make([]*model.KodePosResult, len(list))
	for i, item := range list {
		item := item
		result[i] = &model.KodePosResult{
			KodePos:   item.KodePos,
			Kelurahan: item.Kelurahan,
			Kecamatan: item.Kecamatan,
			Kota:      item.Kota,
			Provinsi:  item.Provinsi,
		}
	}
	return result, nil
}
