package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// KodeBank is the resolver for the kodeBank field.
func (r *queryResolver) KodeBank(ctx context.Context, kode string) (*model.KodeBankResult, error) {
	res, err := r.kodeBankSvc.GetByKode(ctx, kode)
	if err != nil {
		return nil, err
	}
	return &model.KodeBankResult{Kode: res.Kode, Nama: res.Nama}, nil
}

// KodeBankList is the resolver for the kodeBankList field.
func (r *queryResolver) KodeBankList(ctx context.Context) ([]*model.KodeBankResult, error) {
	list := r.kodeBankSvc.ListAll(ctx)
	result := make([]*model.KodeBankResult, len(list))
	for i, b := range list {
		b := b
		result[i] = &model.KodeBankResult{Kode: b.Kode, Nama: b.Nama}
	}
	return result, nil
}
