package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// StasiunKrl is the resolver for the stasiunKRL field.
func (r *queryResolver) StasiunKrl(ctx context.Context) ([]*model.StasiunKrl, error) {
	list, err := r.krlSvc.GetStasiun()
	if err != nil {
		return nil, err
	}
	result := make([]*model.StasiunKrl, len(list))
	for i, s := range list {
		s := s
		result[i] = &model.StasiunKrl{
			StasiunID:   s.StasiunId,
			StasiunNama: s.StasiunNama,
			StasiunKode: s.StasiunKode,
		}
	}
	return result, nil
}

// JadwalKrl is the resolver for the jadwalKRL field.
func (r *queryResolver) JadwalKrl(ctx context.Context, stasiunID string, timeFrom *string, timeTo *string) ([]*model.JadwalKrl, error) {
	from := ""
	to := ""
	if timeFrom != nil {
		from = *timeFrom
	}
	if timeTo != nil {
		to = *timeTo
	}

	list, err := r.krlSvc.GetJadwal(stasiunID, from, to)
	if err != nil {
		return nil, err
	}
	result := make([]*model.JadwalKrl, len(list))
	for i, j := range list {
		j := j
		result[i] = &model.JadwalKrl{
			TrainID:     j.TrainId,
			KaName:      j.KaName,
			RouteName:   j.RouteName,
			DestTime:    j.DestTime,
			DestStasiun: j.DestStasiun,
			ColorCode:   j.ColorCode,
		}
	}
	return result, nil
}
