package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// Kurs is the resolver for the kurs field.
func (r *queryResolver) Kurs(ctx context.Context, mataUang *string) ([]*model.KursResult, error) {
	items, err := r.kursSvc.GetKurs(ctx, mataUang)
	if err != nil {
		return nil, err
	}
	out := make([]*model.KursResult, len(items))
	for i, k := range items {
		out[i] = &model.KursResult{
			MataUang:   k.MataUang,
			KursBeli:   k.KursBeli,
			KursJual:   k.KursJual,
			KursTengah: k.KursTengah,
			Tanggal:    k.Tanggal,
		}
	}
	return out, nil
}
