package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// ValidasiNik is the resolver for the validasiNIK field.
func (r *queryResolver) ValidasiNik(ctx context.Context, nik string) (*model.NIKResult, error) {
	res, err := r.nikSvc.Validasi(ctx, nik)
	if err != nil {
		return nil, err
	}
	return &model.NIKResult{
		Valid:        res.Valid,
		Nik:          res.NIK,
		Provinsi:     res.Provinsi,
		Kota:         res.Kota,
		Kecamatan:    res.Kecamatan,
		TanggalLahir: res.TanggalLahir,
		JenisKelamin: res.JenisKelamin,
		Errors:       res.Errors,
	}, nil
}
