package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// NomorDaruratList is the resolver for the nomorDaruratList field.
func (r *queryResolver) NomorDaruratList(ctx context.Context) ([]*model.NomorDarurat, error) {
	list := r.nomorDaruratSvc.ListAll(ctx)
	result := make([]*model.NomorDarurat, len(list))
	for i, n := range list {
		n := n
		result[i] = &model.NomorDarurat{
			Nomor:    n.Nomor,
			Layanan:  n.Layanan,
			Kategori: n.Kategori,
		}
	}
	return result, nil
}

// NomorDaruratCari is the resolver for the nomorDaruratCari field.
func (r *queryResolver) NomorDaruratCari(ctx context.Context, query string) ([]*model.NomorDarurat, error) {
	list := r.nomorDaruratSvc.Cari(ctx, query)
	result := make([]*model.NomorDarurat, len(list))
	for i, n := range list {
		n := n
		result[i] = &model.NomorDarurat{
			Nomor:    n.Nomor,
			Layanan:  n.Layanan,
			Kategori: n.Kategori,
		}
	}
	return result, nil
}
