package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// PahlawanList is the resolver for the pahlawanList field.
func (r *queryResolver) PahlawanList(ctx context.Context) ([]*model.PahlawanNasional, error) {
	list := r.pahlawanSvc.ListAll(ctx)
	result := make([]*model.PahlawanNasional, len(list))
	for i, p := range list {
		p := p
		result[i] = &model.PahlawanNasional{
			Nama:          p.Nama,
			TahunLahir:    p.TahunLahir,
			TahunWafat:    p.TahunWafat,
			Deskripsi:     p.Deskripsi,
			TahunDiangkat: p.TahunDiangkat,
		}
	}
	return result, nil
}

// PahlawanCari is the resolver for the pahlawanCari field.
func (r *queryResolver) PahlawanCari(ctx context.Context, nama string) ([]*model.PahlawanNasional, error) {
	list := r.pahlawanSvc.Cari(ctx, nama)
	result := make([]*model.PahlawanNasional, len(list))
	for i, p := range list {
		p := p
		result[i] = &model.PahlawanNasional{
			Nama:          p.Nama,
			TahunLahir:    p.TahunLahir,
			TahunWafat:    p.TahunWafat,
			Deskripsi:     p.Deskripsi,
			TahunDiangkat: p.TahunDiangkat,
		}
	}
	return result, nil
}
