package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// Penginapan is the resolver for the penginapan field.
func (r *queryResolver) Penginapan(ctx context.Context, kota string) ([]*model.PenginapanItem, error) {
	list, err := r.penginapanSvc.GetByKota(ctx, kota)
	if err != nil {
		return nil, err
	}
	result := make([]*model.PenginapanItem, len(list))
	for i, item := range list {
		item := item
		result[i] = &model.PenginapanItem{
			ID:      item.ID,
			Nama:    item.Nama,
			Tipe:    item.Tipe,
			Alamat:  item.Alamat,
			Bintang: item.Bintang,
			Telepon: item.Telepon,
			Website: item.Website,
			Lat:     item.Lat,
			Lon:     item.Lon,
		}
	}
	return result, nil
}
