package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// PlatNomor is the resolver for the platNomor field.
func (r *queryResolver) PlatNomor(ctx context.Context, kode string) (*model.PlatNomorResult, error) {
	res, err := r.platNomorSvc.GetByKode(ctx, kode)
	if err != nil {
		return nil, err
	}
	return &model.PlatNomorResult{Kode: res.Kode, Wilayah: res.Wilayah, Provinsi: res.Provinsi}, nil
}
