package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// PresidenList is the resolver for the presidenList field.
func (r *queryResolver) PresidenList(ctx context.Context) ([]*model.Presiden, error) {
	list := r.presidenSvc.ListAll(ctx)
	result := make([]*model.Presiden, len(list))
	for i, p := range list {
		p := p
		result[i] = &model.Presiden{
			Urutan:        p.Urutan,
			Nama:          p.Nama,
			WakilPresiden: p.WakilPresiden,
			MulaiJabatan:  p.MulaiJabatan,
			AkhirJabatan:  p.AkhirJabatan,
		}
	}
	return result, nil
}

// PresidenCari is the resolver for the presidenCari field.
func (r *queryResolver) PresidenCari(ctx context.Context, nama string) ([]*model.Presiden, error) {
	list := r.presidenSvc.Cari(ctx, nama)
	result := make([]*model.Presiden, len(list))
	for i, p := range list {
		p := p
		result[i] = &model.Presiden{
			Urutan:        p.Urutan,
			Nama:          p.Nama,
			WakilPresiden: p.WakilPresiden,
			MulaiJabatan:  p.MulaiJabatan,
			AkhirJabatan:  p.AkhirJabatan,
		}
	}
	return result, nil
}
