package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// PtnList is the resolver for the ptnList field.
func (r *queryResolver) PtnList(ctx context.Context) ([]*model.Ptn, error) {
	list := r.ptnSvc.ListAll(ctx)
	result := make([]*model.Ptn, len(list))
	for i, p := range list {
		p := p
		result[i] = &model.Ptn{
			Nama:       p.Nama,
			Singkatan:  p.Singkatan,
			Kota:       p.Kota,
			Provinsi:   p.Provinsi,
			Akreditasi: p.Akreditasi,
			Jenis:      p.Jenis,
		}
	}
	return result, nil
}

// PtnCari is the resolver for the ptnCari field.
func (r *queryResolver) PtnCari(ctx context.Context, query string) ([]*model.Ptn, error) {
	list := r.ptnSvc.Cari(ctx, query)
	result := make([]*model.Ptn, len(list))
	for i, p := range list {
		p := p
		result[i] = &model.Ptn{
			Nama:       p.Nama,
			Singkatan:  p.Singkatan,
			Kota:       p.Kota,
			Provinsi:   p.Provinsi,
			Akreditasi: p.Akreditasi,
			Jenis:      p.Jenis,
		}
	}
	return result, nil
}
