package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// ValidasiRekening is the resolver for the validasiRekening field.
func (r *queryResolver) ValidasiRekening(ctx context.Context, bank string, noRekening string) (*model.ValidasiRekeningResult, error) {
	res, err := r.rekeningSvc.Validasi(bank, noRekening)
	if err != nil {
		return nil, err
	}
	return &model.ValidasiRekeningResult{
		Valid:      res.Valid,
		Bank:       res.Bank,
		NoRekening: res.NoRekening,
		Panjang:    res.Panjang,
		Keterangan: res.Keterangan,
	}, nil
}
