package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// StasiunKeretaList is the resolver for the stasiunKeretaList field.
func (r *queryResolver) StasiunKeretaList(ctx context.Context) ([]*model.StasiunKereta, error) {
	list := r.stasiunKeretaSvc.ListAll(ctx)
	result := make([]*model.StasiunKereta, len(list))
	for i, s := range list {
		s := s
		result[i] = &model.StasiunKereta{
			Nama:  s.Nama,
			Kode:  s.Kode,
			Jalur: s.Jalur,
			Tipe:  s.Tipe,
			Kota:  s.Kota,
		}
	}
	return result, nil
}

// StasiunKeretaCari is the resolver for the stasiunKeretaCari field.
func (r *queryResolver) StasiunKeretaCari(ctx context.Context, nama string) ([]*model.StasiunKereta, error) {
	list := r.stasiunKeretaSvc.Cari(ctx, nama)
	result := make([]*model.StasiunKereta, len(list))
	for i, s := range list {
		s := s
		result[i] = &model.StasiunKereta{
			Nama:  s.Nama,
			Kode:  s.Kode,
			Jalur: s.Jalur,
			Tipe:  s.Tipe,
			Kota:  s.Kota,
		}
	}
	return result, nil
}
