package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
	"github.com/lisvindanuu/indonesiaql/internal/service"
)

// Terbilang is the resolver for the terbilang field.
func (r *queryResolver) Terbilang(ctx context.Context, angka float64) (*model.TerbilangResult, error) {
	terbilang, err := service.Terbilang(angka)
	if err != nil {
		return nil, err
	}
	return &model.TerbilangResult{
		Angka:     angka,
		Terbilang: terbilang,
	}, nil
}
