package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// UmrList is the resolver for the umrList field.
func (r *queryResolver) UmrList(ctx context.Context, tahun *int) ([]*model.UMRProvinsi, error) {
	list := r.umrSvc.GetAll(tahun)
	result := make([]*model.UMRProvinsi, len(list))
	for i, item := range list {
		item := item
		result[i] = &model.UMRProvinsi{
			Provinsi: item.Provinsi,
			Kode:     item.Kode,
			Upah:     item.Upah,
			Tahun:    item.Tahun,
		}
	}
	return result, nil
}

// Umr is the resolver for the umr field.
func (r *queryResolver) Umr(ctx context.Context, provinsi string) (*model.UMRProvinsi, error) {
	item := r.umrSvc.GetByProvinsi(provinsi)
	if item == nil {
		return nil, nil
	}
	return &model.UMRProvinsi{
		Provinsi: item.Provinsi,
		Kode:     item.Kode,
		Upah:     item.Upah,
		Tahun:    item.Tahun,
	}, nil
}
