package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/graph/model"
)

// WaktuSholat is the resolver for the waktuSholat field.
func (r *queryResolver) WaktuSholat(ctx context.Context, kota string) (*model.WaktuSholatResult, error) {
	res, err := r.waktuSholatSvc.Get(ctx, kota)
	if err != nil {
		return nil, err
	}
	return &model.WaktuSholatResult{
		Kota:    res.Kota,
		Tanggal: res.Tanggal,
		Subuh:   res.Subuh,
		Terbit:  res.Terbit,
		Dzuhur:  res.Dzuhur,
		Ashar:   res.Ashar,
		Maghrib: res.Maghrib,
		Isya:    res.Isya,
	}, nil
}
