package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/lisvindanuu/indonesiaql/internal/domain"
)

// Kelurahan is the resolver for the kelurahan field.
func (r *kecamatanResolver) Kelurahan(ctx context.Context, obj *domain.Kecamatan) ([]*domain.Kelurahan, error) {
	items, err := r.wilayahSvc.ListKelurahan(ctx, obj.Kode)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.Kelurahan, len(items))
	for i := range items {
		out[i] = &items[i]
	}
	return out, nil
}

// Kecamatan is the resolver for the kecamatan field.
func (r *kotaResolver) Kecamatan(ctx context.Context, obj *domain.Kota) ([]*domain.Kecamatan, error) {
	items, err := r.wilayahSvc.ListKecamatan(ctx, obj.Kode)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.Kecamatan, len(items))
	for i := range items {
		out[i] = &items[i]
	}
	return out, nil
}

// Kota is the resolver for the kota field.
func (r *provinsiResolver) Kota(ctx context.Context, obj *domain.Provinsi) ([]*domain.Kota, error) {
	items, err := r.wilayahSvc.ListKota(ctx, obj.Kode)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.Kota, len(items))
	for i := range items {
		out[i] = &items[i]
	}
	return out, nil
}

// ProvinsiList is the resolver for the provinsiList field.
func (r *queryResolver) ProvinsiList(ctx context.Context) ([]*domain.Provinsi, error) {
	items, err := r.wilayahSvc.ListProvinsi(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.Provinsi, len(items))
	for i := range items {
		out[i] = &items[i]
	}
	return out, nil
}

// Provinsi is the resolver for the provinsi field.
func (r *queryResolver) Provinsi(ctx context.Context, kode string) (*domain.Provinsi, error) {
	return r.wilayahSvc.GetProvinsi(ctx, kode)
}

// Kota is the resolver for the kota field.
func (r *queryResolver) Kota(ctx context.Context, kode string) (*domain.Kota, error) {
	return r.wilayahSvc.GetKota(ctx, kode)
}

// SearchWilayah is the resolver for the searchWilayah field.
func (r *queryResolver) SearchWilayah(ctx context.Context, query string, limit *int) ([]*domain.WilayahSearchResult, error) {
	lim := 10
	if limit != nil {
		lim = *limit
	}
	items, err := r.wilayahSvc.Search(ctx, query, lim)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.WilayahSearchResult, len(items))
	for i := range items {
		out[i] = &items[i]
	}
	return out, nil
}

// Kecamatan returns KecamatanResolver implementation.
func (r *Resolver) Kecamatan() KecamatanResolver { return &kecamatanResolver{r} }

// Kota returns KotaResolver implementation.
func (r *Resolver) Kota() KotaResolver { return &kotaResolver{r} }

// Provinsi returns ProvinsiResolver implementation.
func (r *Resolver) Provinsi() ProvinsiResolver { return &provinsiResolver{r} }

type kecamatanResolver struct{ *Resolver }
type kotaResolver struct{ *Resolver }
type provinsiResolver struct{ *Resolver }
