package staticdata

type BankInfo struct { Nama string; KodeTransfer string }

// KodeBank maps transfer code to bank info
var KodeBank = map[string]BankInfo{
	"002": {Nama: "Bank BRI (Bank Rakyat Indonesia)", KodeTransfer: "002"},
	"484": {Nama: "Bank Saqu (Eks Bank Jasa Jakarta)", KodeTransfer: "484"},
	"459": {Nama: "Krom Bank (Eks Bank Bisnis)", KodeTransfer: "459"},
	"057": {Nama: "Bank BNP Paribas Indonesia", KodeTransfer: "057"},
	"564": {Nama: "Bank Mandiri Taspen", KodeTransfer: "564"},
	"014": {Nama: "Bank BCA (Bank Central Asia)", KodeTransfer: "014"},
	"008": {Nama: "Bank Mandiri", KodeTransfer: "008"},
	"009": {Nama: "Bank BNI (Bank Negara Indonesia)", KodeTransfer: "009"},
	"200": {Nama: "Bank Tabungan Negara (Bank BTN)", KodeTransfer: "200"},
	"426": {Nama: "Bank Mega", KodeTransfer: "426"},
	"567": {Nama: "Allo Bank (Eks Bank Harda)", KodeTransfer: "567"},
	"535": {Nama: "SeaBank (Eks Bank Kesejahteraan Ekonomi)", KodeTransfer: "535"},
	"542": {Nama: "Bank Jago (Eks Bank Artos Indonesia)", KodeTransfer: "542"},
	"023": {Nama: "Bank UOB Indonesia", KodeTransfer: "023"},
	"022": {Nama: "Bank CIMB Niaga", KodeTransfer: "022"},
	"213": {Nama: "Bank SMBC Indonesia", KodeTransfer: "213"},
	"013": {Nama: "Permata Bank", KodeTransfer: "013"},
	"016": {Nama: "Bank BII Maybank", KodeTransfer: "016"},
	"153": {Nama: "Bank Sinarmas", KodeTransfer: "153"},
	"950": {Nama: "Bank Commonwealth", KodeTransfer: "950"},
	"028": {Nama: "Bank OCBC NISP", KodeTransfer: "028"},
	"441": {Nama: "KB Bank Bukopin", KodeTransfer: "441"},
	"123": {Nama: "Bank Kalbar", KodeTransfer: "123"},
	"124": {Nama: "Bank Kaltimtara", KodeTransfer: "124"},
	"131": {Nama: "Bank Maluku Malut", KodeTransfer: "131"},
	"157": {Nama: "Bank Maspion", KodeTransfer: "157"},
	"151": {Nama: "Bank Mestika", KodeTransfer: "151"},
	"485": {Nama: "Bank MNC", KodeTransfer: "485"},
	"548": {Nama: "Bank Multiarta Sentosa (Bank Mas)", KodeTransfer: "548"},
	"503": {Nama: "Bank National Nobu", KodeTransfer: "503"},
	"069": {Nama: "Bank of China Jakarta Branch", KodeTransfer: "069"},
	"555": {Nama: "Bank Index", KodeTransfer: "555"},
	"127": {Nama: "Bank SulutGo (Sulawesi Utara dan Gorontalo)", KodeTransfer: "127"},
	"132": {Nama: "Bank Papua", KodeTransfer: "132"},
	"125": {Nama: "Bank Kalteng", KodeTransfer: "125"},
	"026": {Nama: "Bank Lippo", KodeTransfer: "026"},
	"031": {Nama: "Citibank", KodeTransfer: "031"},
	"046": {Nama: "Bank DBS Indonesia", KodeTransfer: "046"},
	"490": {Nama: "Bank Neo Commerce (Akulaku)", KodeTransfer: "490"},
	"789": {Nama: "Indosat Dompetku", KodeTransfer: "789"},
	"911": {Nama: "Telkomsel Tcash/LinkAja", KodeTransfer: "911"},
	"019": {Nama: "Bank Panin", KodeTransfer: "019"},
	"087": {Nama: "Bank HSBC Indonesia", KodeTransfer: "087"},
	"097": {Nama: "Bank Mayapada", KodeTransfer: "097"},
	"451": {Nama: "Bank Syariah Indonesia (BSI)", KodeTransfer: "451"},
	"506": {Nama: "Bank Mega Syariah", KodeTransfer: "506"},
	"947": {Nama: "Bank Aladin Syariah (Eks Bank Maybank Indocorp)", KodeTransfer: "947"},
	"536": {Nama: "Bank BCA Syariah", KodeTransfer: "536"},
	"147": {Nama: "Bank Muamalat", KodeTransfer: "147"},
	"547": {Nama: "Bank BTPN Syariah", KodeTransfer: "547"},
	"521": {Nama: "Bank KB Bukopin Syariah", KodeTransfer: "521"},
	"425": {Nama: "Bank BJB Syariah", KodeTransfer: "425"},
	"517": {Nama: "Bank Panin Dubai Syariah", KodeTransfer: "517"},
	"116": {Nama: "Bank Aceh Syariah", KodeTransfer: "116"},
	"128": {Nama: "Bank NTB Syariah", KodeTransfer: "128"},
	"111": {Nama: "Bank DKI Jakarta", KodeTransfer: "111"},
	"137": {Nama: "Bank BPD Banten", KodeTransfer: "137"},
	"110": {Nama: "Bank Jabar dan Banten (Bank BJB)", KodeTransfer: "110"},
	"112": {Nama: "BPD DIY (Yogyakarta)", KodeTransfer: "112"},
	"113": {Nama: "Bank Jateng", KodeTransfer: "113"},
	"114": {Nama: "Bank Jatim", KodeTransfer: "114"},
	"167": {Nama: "Bank QNB Indonesia", KodeTransfer: "167"},
	"498": {Nama: "Bank SBI Indonesia", KodeTransfer: "498"},
	"501": {Nama: "bLu/Bank Digital BCA", KodeTransfer: "501"},
	"513": {Nama: "Bank Ina Perdana", KodeTransfer: "513"},
	"036": {Nama: "Bank CCB Indonesia", KodeTransfer: "036"},
	"054": {Nama: "Bank Capital Indonesia", KodeTransfer: "054"},
	"037": {Nama: "Bank Artha Graha International", KodeTransfer: "037"},
	"472": {Nama: "Bank Jasa Jakarta", KodeTransfer: "472"},
	"889": {Nama: "BPR KS (BPR Karyajatnika Sadaya)", KodeTransfer: "889"},
	"949": {Nama: "Bank CTBC (China Trust) Indonesia", KodeTransfer: "949"},
	"039": {Nama: "Bank Credit Agricole Indosuez", KodeTransfer: "039"},
	"003": {Nama: "Bank Ekspor Indonesia", KodeTransfer: "003"},
	"020": {Nama: "Bank Arta Niaga Kencana", KodeTransfer: "020"},
	"531": {Nama: "Amar Bank", KodeTransfer: "531"},
	"117": {Nama: "Bank Sumut", KodeTransfer: "117"},
	"118": {Nama: "Bank Nagari", KodeTransfer: "118"},
	"129": {Nama: "Bank BPD Bali", KodeTransfer: "129"},
	"095": {Nama: "Bank Jtrust Indonesia", KodeTransfer: "095"},
	"076": {Nama: "Bank Bumi Arta", KodeTransfer: "076"},
	"119": {Nama: "Bank Riau Kepri", KodeTransfer: "119"},
	"523": {Nama: "Bank Dipo International (Bank Sahabat Sampoerna)", KodeTransfer: "523"},
	"945": {Nama: "IBK Bank Indonesia", KodeTransfer: "945"},
	"126": {Nama: "Bank Sulselbar", KodeTransfer: "126"},
	"120": {Nama: "Bank Sumselbabel", KodeTransfer: "120"},
	"566": {Nama: "Bank Victoria", KodeTransfer: "566"},
	"405": {Nama: "Bank Victoria Syariah", KodeTransfer: "405"},
	"212": {Nama: "Bank Woori Saudara (BWS)", KodeTransfer: "212"},
	"050": {Nama: "Standard Chartered Bank", KodeTransfer: "050"},
	"520": {Nama: "BPR Prima Master Bank", KodeTransfer: "520"},
	"042": {Nama: "Mitsubishi UFJ Financial Group (MUFG)", KodeTransfer: "042"},
}
