package staticdata

type PahlawanInfo struct {
	Nama          string
	TahunLahir    int
	TahunWafat    int
	Deskripsi     string
	TahunDiangkat int
}

var PahlawanNasional = []PahlawanInfo{
	{Nama: "Abdul Halim Majalengka", TahunLahir: 1887, TahunWafat: 1962, Deskripsi: "Aktivis kemerdekaan dan Ulama; Badan Penyelidik Usaha Persiapan Kemerdekaan Indonesia", TahunDiangkat: 2008},
	{Nama: "Abdul Haris Nasution", TahunLahir: 1918, TahunWafat: 2000, Deskripsi: "Jenderal Angkatan Darat; dua kali diangkat sebagai Kepala Staf Angkatan Darat", TahunDiangkat: 2002},
	{Nama: "Abdul Kadir", TahunLahir: 1771, TahunWafat: 1875, Deskripsi: "Bangsawan dari Melawi; menawarkan pengembangan ekonomi; melakukan perlawanan terhadap pasukan kolonial Belanda", TahunDiangkat: 1999},
	{Nama: "Abdul Kahar Mudzakkir", TahunLahir: 1907, TahunWafat: 1973, Deskripsi: "", TahunDiangkat: 2019},
	{Nama: "Abdul Malik Karim Amrullah", TahunLahir: 1908, TahunWafat: 1981, Deskripsi: "Sarjana Islam dan penulis sekaligus tokoh Muhammadiyah.", TahunDiangkat: 2011},
	{Nama: "Abdul Muis", TahunLahir: 1883, TahunWafat: 1959, Deskripsi: "Politisi; Anggota Volksraad; kemudian penulis", TahunDiangkat: 1959},
	{Nama: "Abdulrachman Saleh", TahunLahir: 1909, TahunWafat: 1947, Deskripsi: "Tokoh awal dalam Angkatan Udara; terbunuh ketika membawa keperluan medis karena ditembak oleh Belanda", TahunDiangkat: 1974},
	{Nama: "Abdul Wahab Hasbullah", TahunLahir: 1888, TahunWafat: 1971, Deskripsi: "Tokoh Islam; salah seorang pendiri Nadhlatul Ulama", TahunDiangkat: 2014},
	{Nama: "Andi Abdullah Bau Massepe", TahunLahir: 1918, TahunWafat: 1947, Deskripsi: "Bangsawan Bugis; memimpin penyerangan melawan pasukan Belanda selama Revolusi Nasional; seorang putra dari Andi Mappanyukki", TahunDiangkat: 2005},
	{Nama: "Abdurrahman Baswedan", TahunLahir: 1908, TahunWafat: 1986, Deskripsi: "Nasionalis dan mubaligh yang meyakinkan Mesir untuk mengakui kemerdekaan Indonesia secara de facto", TahunDiangkat: 2018},
	{Nama: "Achmad Subarjo", TahunLahir: 1896, TahunWafat: 1978, Deskripsi: "Aktivis kemerdekaan dan menteri pemerintahan", TahunDiangkat: 2009},
	{Nama: "Adam Malik", TahunLahir: 1917, TahunWafat: 1984, Deskripsi: "Jurnalis dan aktivis kemerdekaan; Wakil Presiden Indonesia ketiga", TahunDiangkat: 1998},
	{Nama: "Adnan Kapau Gani", TahunLahir: 1905, TahunWafat: 1968, Deskripsi: "Aktivis kemerdekaan yang menjadi menteri pemerintahan; menyeludupkan senjata untuk mendukung Revolusi Nasional", TahunDiangkat: 2007},
	{Nama: "Nyi Ageng Serang", TahunLahir: 1752, TahunWafat: 1828, Deskripsi: "Pemimpin gerilyawan Jawa yang memimpin penyerangan terhadap kolonial Belanda atas beberapa pendudukan", TahunDiangkat: 1974},
	{Nama: "Agus Salim", TahunLahir: 1884, TahunWafat: 1954, Deskripsi: "Aktivis kemerdekaan; politisi; pemimpin Islam Minang", TahunDiangkat: 1961},
	{Nama: "Agustinus Adisucipto", TahunLahir: 1916, TahunWafat: 1947, Deskripsi: "Tokoh awal dalam Angkatan Udara; terbunuh ketika membawa keperluan medis karena ditembak oleh Belanda", TahunDiangkat: 1974},
	{Nama: "Ahmad Dahlan", TahunLahir: 1868, TahunWafat: 1934, Deskripsi: "Pemimpin Islam Jawa; mendirikan Muhammadiyah; suami Siti Walidah", TahunDiangkat: 1961},
	{Nama: "Ahmad Rifa'i", TahunLahir: 1786, TahunWafat: 1870, Deskripsi: "Pemikir dan penulis Islam yang dikenal karena pernyataan anti-Belandanya", TahunDiangkat: 2004},
	{Nama: "Ahmad Yani", TahunLahir: 1922, TahunWafat: 1965, Deskripsi: "Pemimpin Angkatan Darat; terbunuh saat Gerakan 30 September", TahunDiangkat: 1965},
	{Nama: "Alexander Andries Maramis", TahunLahir: 1897, TahunWafat: 1977, Deskripsi: "Anggota BPUPKI; Menteri Keuangan Indonesia; dan diplomat", TahunDiangkat: 2019},
	{Nama: "Alimin", TahunLahir: 1889, TahunWafat: 1964, Deskripsi: "Pendukung kemerdekaan; politisi; dan tokoh Partai Komunis Indonesia", TahunDiangkat: 1964},
	{Nama: "Amir Hamzah", TahunLahir: 1911, TahunWafat: 1946, Deskripsi: "Penyair dan nasionalis", TahunDiangkat: 1975},
	{Nama: "Andi Depu", TahunLahir: 1907, TahunWafat: 1985, Deskripsi: "Pejuang dan aktivis yang berhasil mempertahankan pengibaran bendera nasional di Mandar pada 1944; padahal dilarang keras", TahunDiangkat: 2018},
	{Nama: "Antasari", TahunLahir: 1809, TahunWafat: 1862, Deskripsi: "Melakukan penyerangan terhadap pasukan kolonial Belanda dalam Perang Banjar", TahunDiangkat: 1968},
	{Nama: "Arie Frederik Lasut", TahunLahir: 1918, TahunWafat: 1949, Deskripsi: "Geolog dan pengajar yang dieksekusi oleh Belanda", TahunDiangkat: 1969},
	{Nama: "Arnold Mononutu", TahunLahir: 1896, TahunWafat: 1983, Deskripsi: "Menteri Penerangan Indonesia ke-6", TahunDiangkat: 2020},
	{Nama: "As'ad Syamsul Arifin", TahunLahir: 1897, TahunWafat: 1990, Deskripsi: "Ulama; tokoh Nahdlatul Ulama", TahunDiangkat: 2016},
	{Nama: "Baabullah", TahunLahir: 1528, TahunWafat: 1583, Deskripsi: "Penguasa ke-24 Kesultanan Ternate", TahunDiangkat: 2020},
	{Nama: "Bagindo Azizchan", TahunLahir: 1910, TahunWafat: 1947, Deskripsi: "Wali kota Padang; melawan pasukan Belanda saat Revolusi Nasional", TahunDiangkat: 2005},
	{Nama: "Basuki Rahmat", TahunLahir: 1921, TahunWafat: 1969, Deskripsi: "Jenderal; saksi dari Supersemar", TahunDiangkat: 1969},
	{Nama: "Bernard Wilhelm Lapian", TahunLahir: 1892, TahunWafat: 1977, Deskripsi: "Nationalis; pimpinan gereja; dan gubernur kedua Sulawesi", TahunDiangkat: 2015},
	{Nama: "Teungku Chik di Tiro", TahunLahir: 1836, TahunWafat: 1891, Deskripsi: "Tokoh Islam Aceh dan pemimpin gerilyawan yang melakukan perlawanan pasukan kolonial Belanda", TahunDiangkat: 1973},
	{Nama: "Tjilik Riwut", TahunLahir: 1918, TahunWafat: 1987, Deskripsi: "Prajurit dan politisi; menawarkan pengembangan ekonomi dan budaya di Kalimantan Tengah", TahunDiangkat: 1998},
	{Nama: "Tjipto Mangoenkoesoemo", TahunLahir: 1886, TahunWafat: 1943, Deskripsi: "Dokter; salah satu dari Tiga Serangkai; Anggota Volksraad; Tokoh Indische Partij", TahunDiangkat: 1964},
	{Nama: "Tjokroaminoto", TahunLahir: 1883, TahunWafat: 1934, Deskripsi: "Politisi; pemimpin Sarekat Islam; mentor pemimpin-pemimpin bangsa seperti Sukarno; Semaoen; Musso; Alimin; Darsono; Kartosoewirjo; dan Tan Malaka", TahunDiangkat: 1961},
	{Nama: "Ernest Douwes Dekker", TahunLahir: 1879, TahunWafat: 1950, Deskripsi: "Jurnalis dan politisi Indo yang membantu kemerdekaan Indonesia; salah satu dari Tiga Serangkai", TahunDiangkat: 1961},
	{Nama: "Depati Amir", TahunLahir: 1805, TahunWafat: 1869, Deskripsi: "Pejuang yang mempersatukan suku Melayu dengan Tionghoa untuk melawan Belanda", TahunDiangkat: 2018},
	{Nama: "Dewi Sartika", TahunLahir: 1884, TahunWafat: 1947, Deskripsi: "Pengajar; mendirikan sekolah untuk perempuan yang pertama di negara tersebut", TahunDiangkat: 1966},
	{Nama: "Cut Nyak Dhien", TahunLahir: 1850, TahunWafat: 1908, Deskripsi: "Pemimpin gerilyawan Aceh yang melakukan penyerangan terhadap pasukan kolonial belanda; istri Teuku Umar", TahunDiangkat: 1964},
	{Nama: "Diponegoro", TahunLahir: 1785, TahunWafat: 1855, Deskripsi: "Putra Sultan Yogyakarta; melangsungkan perang lima tahun melawan pasukan kolonial Belanda", TahunDiangkat: 1973},
	{Nama: "Donald Izacus Panjaitan", TahunLahir: 1925, TahunWafat: 1965, Deskripsi: "Jenderal Angkatan Darat; terbunuh dalam Gerakan 30 September", TahunDiangkat: 1965},
	{Nama: "Eddy Martadinata", TahunLahir: 1921, TahunWafat: 1966, Deskripsi: "Laksamana Angkatan Laut dan diplomat; terbunuh dalam kecelakaan helikopter", TahunDiangkat: 1966},
	{Nama: "Fakhruddin", TahunLahir: 1890, TahunWafat: 1929, Deskripsi: "Pemimpin Islam; menegosiasikan pengamanan pejiarah haji Indonesia; tokoh Muhammadiyah.", TahunDiangkat: 1964},
	{Nama: "Fatmawati", TahunLahir: 1923, TahunWafat: 1980, Deskripsi: "Pembuat bendera nasional pertama; aktivis sosial; istri Sukarno", TahunDiangkat: 2000},
	{Nama: "Ferdinand Lumbantobing", TahunLahir: 1899, TahunWafat: 1962, Deskripsi: "Dokter dan politisi; memperjuangkan hak asasi pasukan buruh", TahunDiangkat: 1962},
	{Nama: "Frans Kaisiepo", TahunLahir: 1921, TahunWafat: 1979, Deskripsi: "Nasionalis Papua yang membantu dalam akuisisi Papua", TahunDiangkat: 1993},
	{Nama: "Gatot Mangkupraja", TahunLahir: 1896, TahunWafat: 1968, Deskripsi: "Aktivis kemerdekaan dan politisi; menyarankan pembentukan Pembela Tanah Air", TahunDiangkat: 2004},
	{Nama: "Gatot Subroto", TahunLahir: 1907, TahunWafat: 1962, Deskripsi: "Jenderal; deputi ketua staff Angkatan Darat", TahunDiangkat: 1962},
	{Nama: "Halim Perdanakusuma", TahunLahir: 1922, TahunWafat: 1947, Deskripsi: "Tokoh awal dalam Angkatan Udara; terbunuh saat Revolusi Nasional", TahunDiangkat: 1975},
	{Nama: "Hamengkubuwono I", TahunLahir: 1717, TahunWafat: 1792, Deskripsi: "Sultan Yogyakarta; melakukan perlawanan terhadap VOC; mendirikan Yogyakarta", TahunDiangkat: 2006},
	{Nama: "Hamengkubuwono IX", TahunLahir: 1912, TahunWafat: 1988, Deskripsi: "Sultan Yogyakarta; aktivis kemerdekaan; pemimpin militer; dan politisi; Wakil Presiden Indonesia kedua", TahunDiangkat: 1990},
	{Nama: "Harun Bin Said", TahunLahir: 1947, TahunWafat: 1968, Deskripsi: "Mengebom MacDonald House saat konfrontasi Indonesia–Malaysia", TahunDiangkat: 1968},
	{Nama: "Hasan Basry", TahunLahir: 1923, TahunWafat: 1984, Deskripsi: "Prajurit selama Revolusi Nasional Indonesia; mendukung integrasi Kalimantan di Indonesia", TahunDiangkat: 2001},
	{Nama: "Hasanuddin", TahunLahir: 1631, TahunWafat: 1670, Deskripsi: "Sultan Gowa; melakukan perlawanan terhadap pasukan kolonial Belanda", TahunDiangkat: 1973},
	{Nama: "Hasyim Asy'ari", TahunLahir: 1875, TahunWafat: 1947, Deskripsi: "Pemimpin Islam; pendiri Nahdlatul Ulama", TahunDiangkat: 1964},
	{Nama: "Hazairin", TahunLahir: 1906, TahunWafat: 1975, Deskripsi: "Sarjana legal; aktivis kemerdekaan; menteri pemerintahan; dan pengajar", TahunDiangkat: 1999},
	{Nama: "Herman Johannes", TahunLahir: 1912, TahunWafat: 1992, Deskripsi: "Insinyur; membuat senjata selama Revolusi Nasional; membantu pendirian Universitas Gadjah Mada; Rektor Universitas Gadjah Mada", TahunDiangkat: 2009},
	{Nama: "Himayatuddin Muhammad Saidi", TahunLahir: 0, TahunWafat: 1776, Deskripsi: "Penguasa ke-20 dan ke-23 Kesultanan Buton", TahunDiangkat: 2019},
	{Nama: "Ida Anak Agung Gde Agung", TahunLahir: 1921, TahunWafat: 1999, Deskripsi: "Aktivis kemerdekaan dan menteri pemerintahan", TahunDiangkat: 2007},
	{Nama: "Idham Chalid", TahunLahir: 1921, TahunWafat: 2010, Deskripsi: "Pemimpin Nahdlatul Ulama; politisi", TahunDiangkat: 2011},
	{Nama: "Ilyas Yakoub", TahunLahir: 1903, TahunWafat: 1958, Deskripsi: "Aktivis kemerdekaan; politisi; dan anggota pasukan gerilyawan", TahunDiangkat: 1999},
	{Nama: "Imam Bonjol", TahunLahir: 1772, TahunWafat: 1864, Deskripsi: "Tokoh Islam dari Sumatra Barat yang melakukan perlawanan terhadap pasukan kolonial Belanda dalam Perang Padri", TahunDiangkat: 1973},
	{Nama: "Radin Inten II", TahunLahir: 1834, TahunWafat: 1856, Deskripsi: "Bangsawan dari Lampung; memimpin revolusi penyerangan penjajah Belanda", TahunDiangkat: 1986},
	{Nama: "Iskandar Muda", TahunLahir: 1593, TahunWafat: 1636, Deskripsi: "Sultan Aceh; memperluas pengaruh negara", TahunDiangkat: 1993},
	{Nama: "Ismail Marzuki", TahunLahir: 1914, TahunWafat: 1958, Deskripsi: "Komposer yang membuat sejumlah lagu kebangsaan", TahunDiangkat: 2004},
	{Nama: "Iswahyudi", TahunLahir: 1918, TahunWafat: 1947, Deskripsi: "Tokoh awal dalam Angkatan Udara; terbunuh saat Revolusi Nasional", TahunDiangkat: 1975},
	{Nama: "Iwa Kusumasumantri", TahunLahir: 1899, TahunWafat: 1971, Deskripsi: "Aktivis kemerdekaan; ahli hukum; dan politisi", TahunDiangkat: 2002},
	{Nama: "Izaak Huru Doko", TahunLahir: 1913, TahunWafat: 1985, Deskripsi: "Aktivis kemerdekaan dan pengajar; membantu pendirian Universitas Udayana", TahunDiangkat: 2006},
	{Nama: "Jamin Ginting", TahunLahir: 1921, TahunWafat: 1974, Deskripsi: "Pejuang kemerdekaan menentang pemerintah Hindia Belanda di Tanah Karo", TahunDiangkat: 2014},
	{Nama: "Janatin", TahunLahir: 1943, TahunWafat: 1968, Deskripsi: "Mengebom MacDonald House saat konfrontasi Indonesia–Malaysia", TahunDiangkat: 1968},
	{Nama: "Jatikusumo", TahunLahir: 1917, TahunWafat: 1992, Deskripsi: "Jenderal Angkatan Darat dan politisi", TahunDiangkat: 2002},
	{Nama: "Andi Jemma", TahunLahir: 1901, TahunWafat: 1965, Deskripsi: "Aktivis kemerdekaan; memimpin penyerangan melawan pasukan Belanda saar Revolusi Nasional", TahunDiangkat: 2002},
	{Nama: "Johannes Abraham Dimara", TahunLahir: 1916, TahunWafat: 2000, Deskripsi: "Pimpinan tentara Papua yang membantu dalam akuisisi Papua", TahunDiangkat: 2010},
	{Nama: "Johannes Leimena", TahunLahir: 1905, TahunWafat: 1977, Deskripsi: "Menteri Kesehatan Pertama; mengembangkan sistem klinik Puskesmas", TahunDiangkat: 2010},
	{Nama: "Juanda Kartawijaya", TahunLahir: 1911, TahunWafat: 1963, Deskripsi: "Politisi Sunda; Perdana Menteri Indonesia terakhir", TahunDiangkat: 1963},
	{Nama: "Karel Satsuit Tubun", TahunLahir: 1928, TahunWafat: 1965, Deskripsi: "Brigadir polisi; terbunuh saat Gerakan 30 September", TahunDiangkat: 1965},
	{Nama: "Kartini", TahunLahir: 1879, TahunWafat: 1904, Deskripsi: "Tokoh hak asasi perempuan Jawa", TahunDiangkat: 1964},
	{Nama: "Ignatius Joseph Kasimo", TahunLahir: 1900, TahunWafat: 1986, Deskripsi: "Aktivis kemerdekaan; pemimpin Partai Katolik", TahunDiangkat: 2011},
	{Nama: "Kasman Singodimedjo", TahunLahir: 1904, TahunWafat: 1982, Deskripsi: "Jaksa yang merupakan ketua KNIP pertama dan menghapus tujuh kata yang berpotensi memecah umat pada Piagam Jakarta", TahunDiangkat: 2018},
	{Nama: "Katamso Darmokusumo", TahunLahir: 1923, TahunWafat: 1965, Deskripsi: "Jenderal Angkatan Darat; terbunuh saat Gerakan 30 September", TahunDiangkat: 1965},
	{Nama: "I Gusti Ketut Jelantik", TahunLahir: 0, TahunWafat: 1849, Deskripsi: "Pemimpin Bali yang melakukan perlawanan terhadap pasukan kolonial Belanda", TahunDiangkat: 1993},
	{Nama: "I Gusti Ketut Puja", TahunLahir: 1904, TahunWafat: 1957, Deskripsi: "Gubernur Bali pertama", TahunDiangkat: 2011},
	{Nama: "Ki Bagus Hadikusumo", TahunLahir: 1890, TahunWafat: 1954, Deskripsi: "Tokoh Muhammadiyah; aktivis kemerdekaan; tokoh Badan Penyelidik Usaha Persiapan Kemerdekaan Indonesia", TahunDiangkat: 2015},
	{Nama: "Ki Hajar Dewantara", TahunLahir: 1889, TahunWafat: 1959, Deskripsi: "Pengajar dan menteri pemerintahan; mendirikan Taman Siswa; saudara Suryopranoto; salah satu dari Tiga Serangkai", TahunDiangkat: 1959},
	{Nama: "Ki Sarmidi Mangunsarkoro", TahunLahir: 1904, TahunWafat: 1957, Deskripsi: "Pengajar bersama dengan Budi Utomo dan Taman Siswa; menteri pemerintahan", TahunDiangkat: 2011},
	{Nama: "Kiras Bangun", TahunLahir: 1852, TahunWafat: 1942, Deskripsi: "Pemimpin gerilyawan Batak yang melawan penjajah Belanda", TahunDiangkat: 2005},
	{Nama: "Kusumah Atmaja", TahunLahir: 1898, TahunWafat: 1952, Deskripsi: "Ketua Kehakiman Mahkamah Agung Pertama", TahunDiangkat: 1965},
	{Nama: "La Maddukelleng", TahunLahir: 1700, TahunWafat: 1765, Deskripsi: "Bangsawan dari Kesultanan Paser; mengusir pasukan Belanda dari Kerajaan Wajo", TahunDiangkat: 1998},
	{Nama: "Lafran Pane", TahunLahir: 1922, TahunWafat: 1991, Deskripsi: "Pendiri Himpunan Mahasiswa Islam", TahunDiangkat: 2017},
	{Nama: "Lambertus Nicodemus Palar", TahunLahir: 1900, TahunWafat: 1981, Deskripsi: "Diplomat; menegosiasikan pengakuan Indonesia saat Revolusi", TahunDiangkat: 2013},
	{Nama: "John Lie", TahunLahir: 1911, TahunWafat: 1988, Deskripsi: "Laksamana Muda Angkatan Laut; menyeludupkan barang untuk membantu Revolusi Nasional", TahunDiangkat: 2009},
	{Nama: "Machmud Singgirei Rumagesan", TahunLahir: 1885, TahunWafat: 1964, Deskripsi: "", TahunDiangkat: 2020},
	{Nama: "Mahmud Badaruddin II", TahunLahir: 1767, TahunWafat: 1852, Deskripsi: "Sultan Palembang; yang melakukan perlawanan terhadap penjajah Inggris dan Belanda", TahunDiangkat: 1984},
	{Nama: "Sultan Mahmud Riayat Syah", TahunLahir: 1760, TahunWafat: 1812, Deskripsi: "Sultan Johor-Pahang-Riau-Lingga; yang melakukan perlawanan terhadap penjajah Belanda", TahunDiangkat: 2017},
	{Nama: "Malahayati", TahunLahir: 1550, TahunWafat: 1604, Deskripsi: "Pejuang dan bangsawan; melawan pasukan Cornelis de Houtman", TahunDiangkat: 2017},
	{Nama: "Mangkunegara I", TahunLahir: 1725, TahunWafat: 1795, Deskripsi: "Melakukan perlawanan terhadap penjajah Belanda dan antek-anteknya di Jawa Tengah", TahunDiangkat: 1988},
	{Nama: "Andi Mappanyukki", TahunLahir: 1885, TahunWafat: 1967, Deskripsi: "Bangsawan Bugis; memimpin penyerangan melawan pasukan Belanda pada 1920-an dan 30-an; ayah dari Andi Abdullah Bau Massepe", TahunDiangkat: 2004},
	{Nama: "Maria Walanda Maramis", TahunLahir: 1872, TahunWafat: 1924, Deskripsi: "Pendukung hak asasi perempuan dan pengajar", TahunDiangkat: 1969},
	{Nama: "Martha Christina Tiahahu", TahunLahir: 1800, TahunWafat: 1818, Deskripsi: "Gerilyawan dari Maluku yang wafat saat ditahan Belanda", TahunDiangkat: 1969},
	{Nama: "Marthen Indey", TahunLahir: 1912, TahunWafat: 1986, Deskripsi: "Nasionalis dan aktivis kemerdekaan; menawarkan intergrasi Papua di Indonesia", TahunDiangkat: 1993},
	{Nama: "Mas Isman", TahunLahir: 1924, TahunWafat: 1982, Deskripsi: "Pejuang kemerdekaan", TahunDiangkat: 2015},
	{Nama: "Mas Mansur", TahunLahir: 1896, TahunWafat: 1946, Deskripsi: "Sarjana Islam; pemimpin Muhammadiyah", TahunDiangkat: 1964},
	{Nama: "Masykur", TahunLahir: 1904, TahunWafat: 1994, Deskripsi: "", TahunDiangkat: 2019},
	{Nama: "Mas Tirtodarmo Haryono", TahunLahir: 1924, TahunWafat: 1965, Deskripsi: "Jenderal Angkatan Darat; terbunuh saat Gerakan 30 September", TahunDiangkat: 1965},
	{Nama: "Maskun Sumadireja", TahunLahir: 1907, TahunWafat: 1986, Deskripsi: "Aktivis kemerdekaan dan politisi", TahunDiangkat: 2004},
	{Nama: "Cut Nyak Meutia", TahunLahir: 1870, TahunWafat: 1910, Deskripsi: "Pemimpin gerilyawan Aceh yang melakukan perlawanan terhadap pasukan kolonial Belanda", TahunDiangkat: 1964},
	{Nama: "Mohammad Hatta", TahunLahir: 1902, TahunWafat: 1980, Deskripsi: "Aktivis kemerdekaan; Wakil Presiden Indonesia Pertama", TahunDiangkat: 2012},
	{Nama: "Mohammad Husni Thamrin", TahunLahir: 1894, TahunWafat: 1941, Deskripsi: "Politisi dan aktivis kemerdekaan", TahunDiangkat: 1960},
	{Nama: "Mohammad Natsir", TahunLahir: 1908, TahunWafat: 1993, Deskripsi: "Sarjana Islam dan politisi; Perdana Menteri Indonesia kelima", TahunDiangkat: 2008},
	{Nama: "Teuku Muhammad Hasan", TahunLahir: 1906, TahunWafat: 1997, Deskripsi: "Aktivis kemerdekaan; gubernur Sumatra pertama", TahunDiangkat: 2006},
	{Nama: "Muhammad Mangundiprojo", TahunLahir: 1905, TahunWafat: 1988, Deskripsi: "Pejuang kemerdekaan; pemimpin Pertempuran Surabaya", TahunDiangkat: 2014},
	{Nama: "Muhammad Yamin", TahunLahir: 1903, TahunWafat: 1962, Deskripsi: "Penyair yang menjadi politisi dan aktivis kemerdekaan", TahunDiangkat: 1973},
	{Nama: "Moehammad Jasin", TahunLahir: 1920, TahunWafat: 2012, Deskripsi: "Bapak Brimob Kepolisian RI", TahunDiangkat: 2015},
	{Nama: "Muhammad Zainuddin Abdul Madjid", TahunLahir: 1898, TahunWafat: 1997, Deskripsi: "Ulama pendiri Nahdlatul Wathan", TahunDiangkat: 2017},
	{Nama: "Mustopo", TahunLahir: 1913, TahunWafat: 1986, Deskripsi: "Pemimpin saat Pertempuran Surabaya; mendirikan Kampus Kedokteran Gigi Dr. Moestopo", TahunDiangkat: 2007},
	{Nama: "Muwardi", TahunLahir: 1907, TahunWafat: 1948, Deskripsi: "Menangani keamanan saat Proklamasi Kemerdekaan; membangun sebuah rumah saat di Surakarta", TahunDiangkat: 1964},
	{Nama: "Nani Wartabone", TahunLahir: 1907, TahunWafat: 1986, Deskripsi: "Aktivis kemerdekaan dan politisi; membantu memadamkan pemberontakan Permesta", TahunDiangkat: 2003},
	{Nama: "I Gusti Ngurah Made Agung", TahunLahir: 1876, TahunWafat: 1906, Deskripsi: "Raja Badung; melakukan perlawanan terhadap pasukan kolonial Belanda", TahunDiangkat: 2015},
	{Nama: "I Gusti Ngurah Rai", TahunLahir: 1917, TahunWafat: 1946, Deskripsi: "Pemimpin militer Bali saat Revolusi Nasional", TahunDiangkat: 1975},
	{Nama: "Nuku Muhammad Amiruddin", TahunLahir: 1738, TahunWafat: 1805, Deskripsi: "Sultan Tidore; memimpin beberapa pertempuran laut melawan pasukan kolonial Belanda", TahunDiangkat: 1995},
	{Nama: "Noer Alie", TahunLahir: 1914, TahunWafat: 1992, Deskripsi: "Pemimpin Islam dan pengajar; memimpin prajurit saat Revolusi Nasional", TahunDiangkat: 2006},
	{Nama: "Teuku Nyak Arif", TahunLahir: 1899, TahunWafat: 1946, Deskripsi: "Politisi Aceh dan pemimpin perlawanan; gubernur Aceh pertama", TahunDiangkat: 1974},
	{Nama: "Opu Daeng Risaju", TahunLahir: 1880, TahunWafat: 1964, Deskripsi: "Politisi wanita awal; melakukan perlawanan terhadap Belanda saat Revolusi Nasional", TahunDiangkat: 2006},
	{Nama: "Oto Iskandar di Nata", TahunLahir: 1897, TahunWafat: 1945, Deskripsi: "Politisi dan aktivis kemerdekaan", TahunDiangkat: 1973},
	{Nama: "Pajonga Daeng Ngalie", TahunLahir: 1901, TahunWafat: 1958, Deskripsi: "Mengkoordinasikan penyerangan di Sulawesi Selatan saat Revolusi Nasional; menawarkan integrasi nasional", TahunDiangkat: 2006},
	{Nama: "Pakubuwono VI", TahunLahir: 1807, TahunWafat: 1849, Deskripsi: "Susuhunan Surakarta; memberontak melawan pasukan kolonial Belanda", TahunDiangkat: 1964},
	{Nama: "Pakubuwono X", TahunLahir: 1866, TahunWafat: 1939, Deskripsi: "Susuhunan Surakarta; mendukung berbagai proyek untuk kepentingan Pribumi Indonesia", TahunDiangkat: 2011},
	{Nama: "Pangeran Muhammad Noor", TahunLahir: 1901, TahunWafat: 1979, Deskripsi: "Menteri Pekerjaan Umum yang mencanangkan proyek Waduk Riam Kanan; Waduk Karangkates; dan proyek pasang-surut di Sumatra dan Kalimantan sebagai lahan penyedia pangan", TahunDiangkat: 2018},
	{Nama: "Pattimura", TahunLahir: 1783, TahunWafat: 1817, Deskripsi: "Gerilyawan dari Maluku yang melakukan perlawanan terhadap pasukan kolonial Belanda", TahunDiangkat: 1973},
	{Nama: "Pierre Tendean", TahunLahir: 1939, TahunWafat: 1965, Deskripsi: "Prajurit Angkatan Darat; terbunuh saat Gerakan 30 September", TahunDiangkat: 1965},
	{Nama: "Pong Tiku", TahunLahir: 1846, TahunWafat: 1907, Deskripsi: "Bangsawan Toraja; melakukan perlawanan terhadap penjajah Belanda", TahunDiangkat: 2002},
	{Nama: "Raden Mattaher", TahunLahir: 1871, TahunWafat: 1907, Deskripsi: "Pejuang dari Jambi yang melakukan perlawanan terhadap pasukan kolonial Belanda", TahunDiangkat: 2020},
	{Nama: "Raja Ali Haji", TahunLahir: 1809, TahunWafat: 1870, Deskripsi: "Sejarawan dan penyair dari Riau", TahunDiangkat: 2004},
	{Nama: "Raja Haji Fisabilillah", TahunLahir: 1727, TahunWafat: 1784, Deskripsi: "Pejuang dari Riau yang melakukan perlawanan terhadap pasukan kolonial Belanda", TahunDiangkat: 1997},
	{Nama: "Rajiman Wediodiningrat", TahunLahir: 1879, TahunWafat: 1952, Deskripsi: "Ketua BPUPKI; Ketua Dewan Perwakilan Rakyat pertama", TahunDiangkat: 2013},
	{Nama: "Ranggong Daeng Romo", TahunLahir: 1915, TahunWafat: 1947, Deskripsi: "Memimpin pasukan dalam dua pertempuran melawan pasukan Belanda saat Revolusi Nasional", TahunDiangkat: 2001},
	{Nama: "Rasuna Said", TahunLahir: 1910, TahunWafat: 1965, Deskripsi: "Pendukung hak asasi wanita dan nasionalis", TahunDiangkat: 1974},
	{Nama: "Robert Wolter Monginsidi", TahunLahir: 1925, TahunWafat: 1949, Deskripsi: "Gerilyawan di Makassar saat Revolusi Nasional; dieksekusi oleh Belanda", TahunDiangkat: 1973},
	{Nama: "Ruhana Kuddus", TahunLahir: 1884, TahunWafat: 1972, Deskripsi: "Wartawati Indonesia pertama", TahunDiangkat: 2019},
	{Nama: "Saharjo", TahunLahir: 1909, TahunWafat: 1963, Deskripsi: "Menteri Kehakiman; pelopor pengesahan pembaruan di negara tersebut", TahunDiangkat: 1963},
	{Nama: "Sam Ratulangi", TahunLahir: 1890, TahunWafat: 1949, Deskripsi: "Politisi Minahasa dan pendukung kemerdekaan Indonesia", TahunDiangkat: 1961},
	{Nama: "Samanhudi", TahunLahir: 1878, TahunWafat: 1956, Deskripsi: "Pengusaha; mendirikan Sarekat Islam", TahunDiangkat: 1961},
	{Nama: "Sarjito", TahunLahir: 1889, TahunWafat: 1970, Deskripsi: "Dokter; Akademisi; Rektor pertama Universitas Gadjah Mada", TahunDiangkat: 2019},
	{Nama: "Silas Papare", TahunLahir: 1918, TahunWafat: 1978, Deskripsi: "Memperjuangkan kemerdekaan Papua dari Belanda; menawarkan integrasi Papua di Indonesia", TahunDiangkat: 1993},
	{Nama: "Sisingamangaraja XII", TahunLahir: 1849, TahunWafat: 1907, Deskripsi: "Pemimpin Batak yang melakukan kampanye gerilyawan melawan pasukan kolonial Belanda", TahunDiangkat: 1961},
	{Nama: "Siswondo Parman", TahunLahir: 1918, TahunWafat: 1965, Deskripsi: "Jenderal Angkatan Darat; terbunuh saat Gerakan 30 September", TahunDiangkat: 1965},
	{Nama: "Siti Hartinah", TahunLahir: 1923, TahunWafat: 1996, Deskripsi: "Istri presiden Suharto; aktif dalam karya sosial; mendirikan Taman Mini Indonesia Indah", TahunDiangkat: 1996},
	{Nama: "Siti Walidah", TahunLahir: 1872, TahunWafat: 1946, Deskripsi: "Pendiri Aisyiyah; tokoh Muhammadiyah; istri Ahmad Dahlan;", TahunDiangkat: 1971},
	{Nama: "Slamet Rijadi", TahunLahir: 1927, TahunWafat: 1950, Deskripsi: "Brigadir Jeneral Angkatan Darat; terbunuh ketika putting down pemberontakan di Sulawesi", TahunDiangkat: 2007},
	{Nama: "Soedirman", TahunLahir: 1916, TahunWafat: 1950, Deskripsi: "Komandan Ketua Tentara Nasional Indonesia pada saat Revolusi Nasional.", TahunDiangkat: 1964},
	{Nama: "Albertus Soegijapranata", TahunLahir: 1896, TahunWafat: 1963, Deskripsi: "Uskup Katolik Jawa dan nasionalis", TahunDiangkat: 1963},
	{Nama: "Sugiyono Mangunwiyoto", TahunLahir: 1926, TahunWafat: 1965, Deskripsi: "Kolonel Angkatan Darat; terbunuh saat Gerakan 30 September", TahunDiangkat: 1965},
	{Nama: "Suharso", TahunLahir: 1912, TahunWafat: 1971, Deskripsi: "Pelopor pengobatan prostesis", TahunDiangkat: 1973},
	{Nama: "Soekanto Tjokrodiatmodjo", TahunLahir: 1908, TahunWafat: 1993, Deskripsi: "Kepala Kepolisian Negara Republik Indonesia pertama", TahunDiangkat: 2020},
	{Nama: "Sukarjo Wiryopranoto", TahunLahir: 1903, TahunWafat: 1962, Deskripsi: "Tokoh kemerdekaan; diplomat; dan politisi", TahunDiangkat: 1962},
	{Nama: "Sukarni", TahunLahir: 1916, TahunWafat: 1971, Deskripsi: "Tokoh kemerdekaan; diplomat; dan politisi", TahunDiangkat: 2014},
	{Nama: "Soekarno", TahunLahir: 1901, TahunWafat: 1970, Deskripsi: "Aktivis kemerdekaan yang membacakan Proklamasi Kemerdekaan; Presiden Indonesia pertama", TahunDiangkat: 2012},
	{Nama: "Sultan Agung", TahunLahir: 1591, TahunWafat: 1645, Deskripsi: "Sultan Mataram; melakukan perlawanan terhadap VOC", TahunDiangkat: 1975},
	{Nama: "Andi Sultan Daeng Radja", TahunLahir: 1894, TahunWafat: 1963, Deskripsi: "Aktivis kemerdekaan dan politisi", TahunDiangkat: 2006},
	{Nama: "Supeno", TahunLahir: 1916, TahunWafat: 1949, Deskripsi: "Menteri pemerintahan; terbunuh ketika perlawanan terhadap Belanda saat Revolusi Nasional", TahunDiangkat: 1970},
	{Nama: "Supomo", TahunLahir: 1903, TahunWafat: 1958, Deskripsi: "Menteri Kehakiman Pertama; membantu penulisan Konstitusi", TahunDiangkat: 1965},
	{Nama: "Suprapto", TahunLahir: 1920, TahunWafat: 1965, Deskripsi: "Jenderal Angkatan Darat; terbunuh saat Gerakan 30 September", TahunDiangkat: 1965},
	{Nama: "Supriyadi", TahunLahir: 1925, TahunWafat: 1945, Deskripsi: "Pemimpin pemberontakan melawan pasukan pendudukan Jepang di Blitar", TahunDiangkat: 1975},
	{Nama: "Suroso", TahunLahir: 1893, TahunWafat: 1981, Deskripsi: "Politisi dan aktivis kemerdekaan; Wakil Ketua BPUPKI; Gubernur pertama Jawa Tengah; Bapak Koperasi Pegawai Negeri Republik Indonesia", TahunDiangkat: 1986},
	{Nama: "Suryo", TahunLahir: 1896, TahunWafat: 1948, Deskripsi: "Gubernur pertama Jawa Timur yang merupakan tokoh sentral Pertempuran Surabaya", TahunDiangkat: 1964},
	{Nama: "Suryopranoto", TahunLahir: 1871, TahunWafat: 1959, Deskripsi: "Pengajar dan tokoh hak-hak buruh; saudara Ki Hajar Dewantara", TahunDiangkat: 1959},
	{Nama: "Sutan Mohammad Amin Nasution", TahunLahir: 1904, TahunWafat: 1993, Deskripsi: "Gubernur Sumatra Utara dan Riau ke-1", TahunDiangkat: 2020},
	{Nama: "Sutan Syahrir", TahunLahir: 1909, TahunWafat: 1966, Deskripsi: "Politisi; Perdana Menteri Indonesia pertama", TahunDiangkat: 1966},
	{Nama: "Soetomo", TahunLahir: 1888, TahunWafat: 1938, Deskripsi: "dokter; pengajar Jawa; mendirikan Budi Utomo", TahunDiangkat: 1961},
	{Nama: "Sutomo", TahunLahir: 1920, TahunWafat: 1981, Deskripsi: "Pemimpin militer yang memimpin perlawanan dalam Pertempuran Surabaya", TahunDiangkat: 2008},
	{Nama: "Sutoyo Siswomiharjo", TahunLahir: 1922, TahunWafat: 1965, Deskripsi: "Jenderal Angkatan Darat; terbunuh saat Gerakan 30 September", TahunDiangkat: 1965},
	{Nama: "Syafruddin Prawiranegara", TahunLahir: 1911, TahunWafat: 1989, Deskripsi: "Gubernur Bank Indonesia pertama", TahunDiangkat: 2011},
	{Nama: "Syam'un", TahunLahir: 1894, TahunWafat: 1949, Deskripsi: "Pejuang yang pernah bergabung dalam PETA dan BKR; serta menentang pemerintahan Hindia Belanda di Banten. Pendiri Pesantren Al-Khairiyah Cilegon; Banten", TahunDiangkat: 2018},
	{Nama: "Syarif Kasim II", TahunLahir: 1893, TahunWafat: 1968, Deskripsi: "Sultan Siak; menawarkan integrasi kerajaan-kerajaan di Sumatra Timur", TahunDiangkat: 1998},
	{Nama: "Tahi Bonar Simatupang", TahunLahir: 1920, TahunWafat: 1990, Deskripsi: "Jenderal yang menjabat sebagai ketua staff dari 1950 sampai 1954", TahunDiangkat: 2013},
	{Nama: "Tuanku Tambusai", TahunLahir: 1784, TahunWafat: 1882, Deskripsi: "Pemimpin Islam dari Riau yang melakukan perlawanan terhadap pasukan kolonial Belanda saat Perang Padri", TahunDiangkat: 1995},
	{Nama: "Tan Malaka", TahunLahir: 1884, TahunWafat: 1949, Deskripsi: "Politisi dan intelektual asal Minang. Ia menyumbangkan gagasannya dalam beberapa karya; terutama Madilog (Materialistik; Dialog; dan Logika). Pendiri Partai Murba; tokoh Partai Komunis Indonesia", TahunDiangkat: 1963},
	{Nama: "Thaha Syaifuddin", TahunLahir: 1816, TahunWafat: 1904, Deskripsi: "Sultan Jambi; memimpin pasukan revolusi melawan pasukan kolonial Belanda", TahunDiangkat: 1977},
	{Nama: "Tirtayasa", TahunLahir: 1631, TahunWafat: 1683, Deskripsi: "Sultan Banten yang melakukan perlawanan terhadap Belanda", TahunDiangkat: 1970},
	{Nama: "Tirto Adhi Suryo", TahunLahir: 1880, TahunWafat: 1918, Deskripsi: "Jurnalis; diasingkan karena editorial anti-Belanda buatannya", TahunDiangkat: 2006},
	{Nama: "Teuku Umar", TahunLahir: 1854, TahunWafat: 1899, Deskripsi: "Pemimpin gerilyawan Aceh yang melakukan perlawanan terhadap pasukan kolonial Belanda; suami Cut Nyak Dhien", TahunDiangkat: 1973},
	{Nama: "Untung Surapati", TahunLahir: 1660, TahunWafat: 1706, Deskripsi: "Memimpin beberapa pemberontakan melawan VOC", TahunDiangkat: 1975},
	{Nama: "Urip Sumoharjo", TahunLahir: 1893, TahunWafat: 1948, Deskripsi: "Pemimpin Angkatan Darat Indonesia; komandan kedua setelah Sudirman", TahunDiangkat: 1964},
	{Nama: "Wage Rudolf Supratman", TahunLahir: 1903, TahunWafat: 1938, Deskripsi: "Komposer lagu kebangsaan Indonesia Raya", TahunDiangkat: 1971},
	{Nama: "Wahid Hasyim", TahunLahir: 1914, TahunWafat: 1953, Deskripsi: "Pemimpin Nahdlatul Ulama; Menteri Agama Indonesia pertama", TahunDiangkat: 1964},
	{Nama: "Wahidin Sudirohusodo", TahunLahir: 1852, TahunWafat: 1917, Deskripsi: "Dokter dan pemimpin di Budi Utomo", TahunDiangkat: 1973},
	{Nama: "Wilhelmus Zakaria Johannes", TahunLahir: 1895, TahunWafat: 1952, Deskripsi: "Pelopor pengobatan radiologi", TahunDiangkat: 1968},
	{Nama: "Yos Sudarso", TahunLahir: 1925, TahunWafat: 1962, Deskripsi: "Komodor Angkatan Laut; terbunuh saat konfrontasi dengan Belanda di Nugini Belanda", TahunDiangkat: 1973},
	{Nama: "Yusuf Tajul Khalwati", TahunLahir: 1626, TahunWafat: 1699, Deskripsi: "Pemimpin Islam; memimpin pemberontakan gerilyawan melawan VOC", TahunDiangkat: 1995},
	{Nama: "Zainal Mustafa", TahunLahir: 1907, TahunWafat: 1944, Deskripsi: "Pemimpin Islam yang melakukan perlawanan terhadap pasukan pendudukan Jepang", TahunDiangkat: 1972},
	{Nama: "Zainul Arifin", TahunLahir: 1909, TahunWafat: 1963, Deskripsi: "Politisi dan gerilyawan; terbunuh saat peristiwa percobaan pembunuhan yang ditargetkan kepada Sukarno", TahunDiangkat: 1963},
}
