package staticdata

type PTNInfo struct {
	Nama       string
	Singkatan  string
	Kota       string
	Provinsi   string
	Akreditasi string
	Jenis      string
}

var DaftarPTN = []PTNInfo{
	{"Universitas Indonesia", "UI", "Depok", "Jawa Barat", "Unggul", "Universitas"},
	{"Universitas Gadjah Mada", "UGM", "Yogyakarta", "DI Yogyakarta", "Unggul", "Universitas"},
	{"Institut Teknologi Bandung", "ITB", "Bandung", "Jawa Barat", "Unggul", "Institut"},
	{"Institut Pertanian Bogor", "IPB", "Bogor", "Jawa Barat", "Unggul", "Institut"},
	{"Universitas Airlangga", "UNAIR", "Surabaya", "Jawa Timur", "Unggul", "Universitas"},
	{"Institut Teknologi Sepuluh Nopember", "ITS", "Surabaya", "Jawa Timur", "Unggul", "Institut"},
	{"Universitas Padjadjaran", "UNPAD", "Bandung", "Jawa Barat", "Unggul", "Universitas"},
	{"Universitas Diponegoro", "UNDIP", "Semarang", "Jawa Tengah", "Unggul", "Universitas"},
	{"Universitas Brawijaya", "UB", "Malang", "Jawa Timur", "Unggul", "Universitas"},
	{"Universitas Hasanuddin", "UNHAS", "Makassar", "Sulawesi Selatan", "Unggul", "Universitas"},
	{"Universitas Pendidikan Indonesia", "UPI", "Bandung", "Jawa Barat", "Unggul", "Universitas"},
	{"Universitas Sebelas Maret", "UNS", "Surakarta", "Jawa Tengah", "Unggul", "Universitas"},
	{"Universitas Negeri Malang", "UM", "Malang", "Jawa Timur", "Unggul", "Universitas"},
	{"Universitas Negeri Yogyakarta", "UNY", "Yogyakarta", "DI Yogyakarta", "Unggul", "Universitas"},
	{"Universitas Negeri Semarang", "UNNES", "Semarang", "Jawa Tengah", "Unggul", "Universitas"},
	{"Universitas Negeri Jakarta", "UNJ", "Jakarta", "DKI Jakarta", "Unggul", "Universitas"},
	{"Universitas Negeri Surabaya", "UNESA", "Surabaya", "Jawa Timur", "Unggul", "Universitas"},
	{"Universitas Negeri Padang", "UNP", "Padang", "Sumatera Barat", "Unggul", "Universitas"},
	{"Universitas Negeri Makassar", "UNM", "Makassar", "Sulawesi Selatan", "Unggul", "Universitas"},
	{"Universitas Syiah Kuala", "USK", "Banda Aceh", "Aceh", "Unggul", "Universitas"},
	{"Universitas Sumatera Utara", "USU", "Medan", "Sumatera Utara", "Unggul", "Universitas"},
	{"Universitas Andalas", "UNAND", "Padang", "Sumatera Barat", "Unggul", "Universitas"},
	{"Universitas Sriwijaya", "UNSRI", "Palembang", "Sumatera Selatan", "Unggul", "Universitas"},
	{"Universitas Lampung", "UNILA", "Bandar Lampung", "Lampung", "Unggul", "Universitas"},
	{"Universitas Sam Ratulangi", "UNSRAT", "Manado", "Sulawesi Utara", "Unggul", "Universitas"},
	{"Universitas Udayana", "UNUD", "Denpasar", "Bali", "Unggul", "Universitas"},
	{"Universitas Jember", "UNEJ", "Jember", "Jawa Timur", "Unggul", "Universitas"},
	{"Universitas Negeri Gorontalo", "UNG", "Gorontalo", "Gorontalo", "Unggul", "Universitas"},
	{"UIN Sunan Kalijaga", "UIN-SUKA", "Yogyakarta", "DI Yogyakarta", "Unggul", "Universitas"},
	{"UIN Ar-Raniry", "UIN-ARRANIRY", "Banda Aceh", "Aceh", "Unggul", "Universitas"},
	{"UIN Maulana Malik Ibrahim", "UIN-MALIKI", "Malang", "Jawa Timur", "Unggul", "Universitas"},
	{"UIN Raden Fatah", "UIN-RF", "Palembang", "Sumatera Selatan", "Unggul", "Universitas"},
	{"UIN Syarif Hidayatullah", "UIN-JKT", "Jakarta", "DKI Jakarta", "Unggul", "Universitas"},
	{"Politeknik Elektronika Negeri Surabaya", "PENS", "Surabaya", "Jawa Timur", "Unggul", "Politeknik"},
	{"Politeknik Ilmu Pelayaran Semarang", "PIPS", "Semarang", "Jawa Tengah", "Unggul", "Politeknik"},
	{"Politeknik Negeri Bandung", "POLBAN", "Bandung", "Jawa Barat", "Unggul", "Politeknik"},
	{"Politeknik Pariwisata NHI Bandung", "PNHI", "Bandung", "Jawa Barat", "Unggul", "Politeknik"},
	{"Politeknik Negeri Jakarta", "PNJ", "Jakarta", "DKI Jakarta", "Unggul", "Politeknik"},
	{"Universitas Riau", "UNRI", "Pekanbaru", "Riau", "Baik Sekali", "Universitas"},
	{"Universitas Jambi", "UNJA", "Jambi", "Jambi", "Baik Sekali", "Universitas"},
	{"Universitas Bengkulu", "UNIB", "Bengkulu", "Bengkulu", "Baik Sekali", "Universitas"},
	{"Universitas Sultan Ageng Tirtayasa", "UNTIRTA", "Serang", "Banten", "Baik Sekali", "Universitas"},
	{"Universitas Tanjungpura", "UNTAN", "Pontianak", "Kalimantan Barat", "Baik Sekali", "Universitas"},
	{"Universitas Palangka Raya", "UPR", "Palangka Raya", "Kalimantan Tengah", "Baik Sekali", "Universitas"},
	{"Universitas Lambung Mangkurat", "ULM", "Banjarmasin", "Kalimantan Selatan", "Baik Sekali", "Universitas"},
	{"Universitas Mulawarman", "UNMUL", "Samarinda", "Kalimantan Timur", "Baik Sekali", "Universitas"},
	{"Universitas Tadulako", "UNTAD", "Palu", "Sulawesi Tengah", "Baik Sekali", "Universitas"},
	{"Universitas Halu Oleo", "UHO", "Kendari", "Sulawesi Tenggara", "Baik Sekali", "Universitas"},
	{"Universitas Mataram", "UNRAM", "Mataram", "Nusa Tenggara Barat", "Baik Sekali", "Universitas"},
	{"Universitas Nusa Cendana", "UNDANA", "Kupang", "Nusa Tenggara Timur", "Baik Sekali", "Universitas"},
	{"Universitas Pattimura", "UNPATTI", "Ambon", "Maluku", "Baik Sekali", "Universitas"},
	{"Universitas Bangka Belitung", "UBB", "Pangkalpinang", "Kepulauan Bangka Belitung", "Baik Sekali", "Universitas"},
	{"Universitas Negeri Medan", "UNIMED", "Medan", "Sumatera Utara", "Baik Sekali", "Universitas"},
	{"UIN Sultan Syarif Kasim", "UIN-SUSKA", "Pekanbaru", "Riau", "Baik Sekali", "Universitas"},
	{"UIN Imam Bonjol", "UIN-IB", "Padang", "Sumatera Barat", "Baik Sekali", "Universitas"},
	{"Universitas Siliwangi", "UNSIL", "Tasikmalaya", "Jawa Barat", "Baik Sekali", "Universitas"},
	{"Universitas Borneo Tarakan", "UBT", "Tarakan", "Kalimantan Utara", "Baik", "Universitas"},
	{"Universitas Sulawesi Barat", "UNSULBAR", "Majene", "Sulawesi Barat", "Baik", "Universitas"},
	{"Universitas Khairun", "UNKHAIR", "Ternate", "Maluku Utara", "Baik", "Universitas"},
	{"Universitas Papua", "UNIPA", "Manokwari", "Papua Barat", "Baik", "Universitas"},
	{"Universitas Cenderawasih", "UNCEN", "Jayapura", "Papua", "Baik", "Universitas"},
	{"Universitas Maritim Raja Ali Haji", "UMRAH", "Tanjungpinang", "Kepulauan Riau", "Baik", "Universitas"},
}
