package staticdata

type StasiunKeretaInfo struct {
	Nama  string
	Kode  string
	Jalur string
	Tipe  string
	Kota  string
}

var DaftarStasiunKereta = []StasiunKeretaInfo{
	{"Jakarta Kota", "JKT", "KRL Bogor", "KRL", "Jakarta"},
	{"Jayakarta", "JAY", "KRL Bogor", "KRL", "Jakarta"},
	{"Mangga Besar", "MGB", "KRL Bogor", "KRL", "Jakarta"},
	{"Sawah Besar", "SWB", "KRL Bogor", "KRL", "Jakarta"},
	{"Juanda", "JUA", "KRL Bogor", "KRL", "Jakarta"},
	{"Gondangdia", "GDD", "KRL Bogor", "KRL", "Jakarta"},
	{"Cikini", "CKI", "KRL Bogor", "KRL", "Jakarta"},
	{"Manggarai", "MRI", "KRL Bogor", "KRL", "Jakarta"},
	{"Tebet", "TBT", "KRL Bogor", "KRL", "Jakarta"},
	{"Cawang", "CWG", "KRL Bogor", "KRL", "Jakarta"},
	{"Duren Kalibata", "DKA", "KRL Bogor", "KRL", "Jakarta"},
	{"Pasar Minggu Baru", "PSB", "KRL Bogor", "KRL", "Jakarta"},
	{"Pasar Minggu", "PSM", "KRL Bogor", "KRL", "Jakarta"},
	{"Tanjung Barat", "TJB", "KRL Bogor", "KRL", "Jakarta"},
	{"Lenteng Agung", "LNA", "KRL Bogor", "KRL", "Depok"},
	{"Universitas Pancasila", "UP", "KRL Bogor", "KRL", "Depok"},
	{"Universitas Indonesia", "UI", "KRL Bogor", "KRL", "Depok"},
	{"Pondok Cina", "POC", "KRL Bogor", "KRL", "Depok"},
	{"Depok Baru", "DPB", "KRL Bogor", "KRL", "Depok"},
	{"Depok", "DPK", "KRL Bogor", "KRL", "Depok"},
	{"Citayam", "CTA", "KRL Bogor", "KRL", "Depok"},
	{"Bojong Gede", "BJG", "KRL Bogor", "KRL", "Bogor"},
	{"Cilebut", "CLB", "KRL Bogor", "KRL", "Bogor"},
	{"Bogor", "BOO", "KRL Bogor", "KRL", "Bogor"},
	{"Pondok Rajeg", "PRJ", "KRL Bogor", "KRL", "Bogor"},
	{"Cibinong", "CBN", "KRL Bogor", "KRL", "Bogor"},
	{"Nambo", "NBO", "KRL Bogor", "KRL", "Bogor"},
	{"Jatinegara", "JNG", "KRL Cikarang", "KRL", "Jakarta"},
	{"Klender", "KLD", "KRL Cikarang", "KRL", "Jakarta"},
	{"Buaran", "BUA", "KRL Cikarang", "KRL", "Jakarta"},
	{"Klender Baru", "KLB", "KRL Cikarang", "KRL", "Jakarta"},
	{"Cakung", "CKG", "KRL Cikarang", "KRL", "Jakarta"},
	{"Kranji", "KRJ", "KRL Cikarang", "KRL", "Bekasi"},
	{"Bekasi", "BKS", "KRL Cikarang", "KRL", "Bekasi"},
	{"Bekasi Timur", "BKT", "KRL Cikarang", "KRL", "Bekasi"},
	{"Tambun", "TBN", "KRL Cikarang", "KRL", "Bekasi"},
	{"Cibitung", "CBT", "KRL Cikarang", "KRL", "Bekasi"},
	{"Metland Telaga Murni", "MTM", "KRL Cikarang", "KRL", "Bekasi"},
	{"Cikarang", "CKR", "KRL Cikarang", "KRL", "Bekasi"},
	{"Tanah Abang", "THB", "KRL Cikarang", "KRL", "Jakarta"},
	{"Karet", "KRT", "KRL Cikarang", "KRL", "Jakarta"},
	{"Sudirman", "SDR", "KRL Cikarang", "KRL", "Jakarta"},
	{"Matraman", "MTR", "KRL Cikarang", "KRL", "Jakarta"},
	{"Angke", "AK", "KRL Cikarang", "KRL", "Jakarta"},
	{"Kampung Bandan", "KPB", "KRL Cikarang", "KRL", "Jakarta"},
	{"Rajawali", "RJW", "KRL Cikarang", "KRL", "Jakarta"},
	{"Kemayoran", "KMY", "KRL Cikarang", "KRL", "Jakarta"},
	{"Pasar Senen", "PSE", "KRL Cikarang", "KRL", "Jakarta"},
	{"Gang Sentiong", "GGS", "KRL Cikarang", "KRL", "Jakarta"},
	{"Kramat", "KRM", "KRL Cikarang", "KRL", "Jakarta"},
	{"Pondok Jati", "PDJ", "KRL Cikarang", "KRL", "Jakarta"},
	{"Palmerah", "PLM", "KRL Rangkasbitung", "KRL", "Jakarta"},
	{"Kebayoran", "KBY", "KRL Rangkasbitung", "KRL", "Jakarta"},
	{"Pondok Ranji", "PDR", "KRL Rangkasbitung", "KRL", "Tangerang Selatan"},
	{"Jurangmangu", "JRG", "KRL Rangkasbitung", "KRL", "Tangerang Selatan"},
	{"Sudimara", "SDM", "KRL Rangkasbitung", "KRL", "Tangerang Selatan"},
	{"Rawa Buntu", "RWB", "KRL Rangkasbitung", "KRL", "Tangerang Selatan"},
	{"Serpong", "SRP", "KRL Rangkasbitung", "KRL", "Tangerang Selatan"},
	{"Cisauk", "CSK", "KRL Rangkasbitung", "KRL", "Tangerang"},
	{"Cicayur", "CCY", "KRL Rangkasbitung", "KRL", "Tangerang"},
	{"Parung Panjang", "PPJ", "KRL Rangkasbitung", "KRL", "Bogor"},
	{"Cilejit", "CLJ", "KRL Rangkasbitung", "KRL", "Bogor"},
	{"Daru", "DRU", "KRL Rangkasbitung", "KRL", "Bogor"},
	{"Tenjo", "TNJ", "KRL Rangkasbitung", "KRL", "Bogor"},
	{"Tigaraksa", "TGR", "KRL Rangkasbitung", "KRL", "Tangerang"},
	{"Cikoya", "CKY", "KRL Rangkasbitung", "KRL", "Tangerang"},
	{"Maja", "MAJ", "KRL Rangkasbitung", "KRL", "Lebak"},
	{"Citeras", "CTR", "KRL Rangkasbitung", "KRL", "Lebak"},
	{"Rangkasbitung", "RKB", "KRL Rangkasbitung", "KRL", "Lebak"},
	{"Tangerang", "TNG", "KRL Tangerang", "KRL", "Tangerang"},
	{"Tanah Tinggi", "TTG", "KRL Tangerang", "KRL", "Tangerang"},
	{"Batu Ceper", "BCP", "KRL Tangerang", "KRL", "Tangerang"},
	{"Poris", "PRS", "KRL Tangerang", "KRL", "Tangerang"},
	{"Kalideres", "KLD2", "KRL Tangerang", "KRL", "Jakarta"},
	{"Rawa Buaya", "RWY", "KRL Tangerang", "KRL", "Jakarta"},
	{"Bojong Indah", "BJI", "KRL Tangerang", "KRL", "Jakarta"},
	{"Taman Kota", "TMK", "KRL Tangerang", "KRL", "Jakarta"},
	{"Pesing", "PSG", "KRL Tangerang", "KRL", "Jakarta"},
	{"Grogol", "GRG", "KRL Tangerang", "KRL", "Jakarta"},
	{"Duri", "DRI", "KRL Tangerang", "KRL", "Jakarta"},
	{"Tanjung Priok", "TPK", "KRL Tanjung Priok", "KRL", "Jakarta"},
	{"Ancol", "ANC", "KRL Tanjung Priok", "KRL", "Jakarta"},
	{"Jambu Baru", "JBR", "KRL Merak", "KRL", "Lebak"},
	{"Catang", "CAT", "KRL Merak", "KRL", "Serang"},
	{"Cikeusal", "CKS", "KRL Merak", "KRL", "Serang"},
	{"Walantaka", "WLT", "KRL Merak", "KRL", "Serang"},
	{"Serang", "SRG", "KRL Merak", "KRL", "Serang"},
	{"Karangantu", "KGT", "KRL Merak", "KRL", "Serang"},
	{"Tonjong Baru", "TNB", "KRL Merak", "KRL", "Serang"},
	{"Cilegon", "CLG", "KRL Merak", "KRL", "Cilegon"},
	{"Krenceng", "KRC", "KRL Merak", "KRL", "Cilegon"},
	{"Merak", "MRK", "KRL Merak", "KRL", "Cilegon"},
	{"Lebak Bulus Grab", "LBB", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Fatmawati", "FTM", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Cipete Raya", "CPR", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Haji Nawi", "HJN", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Blok A", "BLA", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Blok M BCA", "BLM", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"ASEAN", "ASN", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Senayan", "SEN", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Istora Mandiri", "IST", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Bendungan Hilir", "BDH", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Setiabudi Astra", "STB", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Dukuh Atas BNI", "DKA2", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Bundaran HI", "BHI", "MRT Utara-Selatan", "MRT", "Jakarta"},
	{"Setiabudi", "STB2", "LRT Jabodebek Cibubur", "LRT", "Jakarta"},
	{"Rasuna Said", "RSD", "LRT Jabodebek Cibubur", "LRT", "Jakarta"},
	{"Kuningan", "KNN", "LRT Jabodebek Cibubur", "LRT", "Jakarta"},
	{"Pancoran Bank BJB", "PCB", "LRT Jabodebek Cibubur", "LRT", "Jakarta"},
	{"Cikoko", "CKK", "LRT Jabodebek Cibubur", "LRT", "Jakarta"},
	{"Ciliwung", "CLW", "LRT Jabodebek Cibubur", "LRT", "Jakarta"},
	{"TMII", "TMI", "LRT Jabodebek Cibubur", "LRT", "Jakarta"},
	{"Kampung Rambutan", "KPR", "LRT Jabodebek Cibubur", "LRT", "Jakarta"},
	{"Ciracas", "CRC", "LRT Jabodebek Cibubur", "LRT", "Jakarta"},
	{"Harjamukti", "HJM", "LRT Jabodebek Cibubur", "LRT", "Depok"},
	{"Halim", "HLM", "LRT Jabodebek Bekasi", "LRT", "Jakarta"},
	{"Jati Bening Baru", "JBB", "LRT Jabodebek Bekasi", "LRT", "Bekasi"},
	{"Cikunir 1", "CK1", "LRT Jabodebek Bekasi", "LRT", "Bekasi"},
	{"Cikunir 2", "CK2", "LRT Jabodebek Bekasi", "LRT", "Bekasi"},
	{"Bekasi Barat", "BKB", "LRT Jabodebek Bekasi", "LRT", "Bekasi"},
	{"Jati Mulya", "JTM", "LRT Jabodebek Bekasi", "LRT", "Bekasi"},
}
