// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CuacaResult struct {
	Provinsi  string       `json:"provinsi"`
	Kota      string       `json:"kota"`
	Prakiraan []*Prakiraan `json:"prakiraan"`
}

type GempaItem struct {
	Tanggal   string `json:"tanggal"`
	Jam       string `json:"jam"`
	Magnitude string `json:"magnitude"`
	Kedalaman string `json:"kedalaman"`
	Lintang   string `json:"lintang"`
	Bujur     string `json:"bujur"`
	Wilayah   string `json:"wilayah"`
	Potensi   string `json:"potensi"`
	Dirasakan string `json:"dirasakan"`
}

type HargaBBMItem struct {
	Nama   string `json:"nama"`
	Harga  int    `json:"harga"`
	Satuan string `json:"satuan"`
	Jenis  string `json:"jenis"`
}

type KalenderHijriyahResult struct {
	TanggalMasehi   string `json:"tanggalMasehi"`
	TanggalHijriyah string `json:"tanggalHijriyah"`
	Hari            string `json:"hari"`
	HariArab        string `json:"hariArab"`
	Bulan           string `json:"bulan"`
	BulanArab       string `json:"bulanArab"`
	Tahun           int    `json:"tahun"`
}

type KalenderJawaResult struct {
	TanggalMasehi   string `json:"tanggalMasehi"`
	Hari            string `json:"hari"`
	Pasaran         string `json:"pasaran"`
	Wuku            string `json:"wuku"`
	TahunJawa       int    `json:"tahunJawa"`
	NamaWindu       string `json:"namaWindu"`
	TahunDalamWindu string `json:"tahunDalamWindu"`
}

type KodeBankResult struct {
	Kode string `json:"kode"`
	Nama string `json:"nama"`
}

type KodePosResult struct {
	KodePos   string `json:"kodePos"`
	Kelurahan string `json:"kelurahan"`
	Kecamatan string `json:"kecamatan"`
	Kota      string `json:"kota"`
	Provinsi  string `json:"provinsi"`
}

type KursResult struct {
	MataUang   string  `json:"mataUang"`
	KursBeli   float64 `json:"kursBeli"`
	KursJual   float64 `json:"kursJual"`
	KursTengah float64 `json:"kursTengah"`
	Tanggal    string  `json:"tanggal"`
}

type NIKResult struct {
	Valid        bool     `json:"valid"`
	Nik          string   `json:"nik"`
	Provinsi     *string  `json:"provinsi,omitempty"`
	Kota         *string  `json:"kota,omitempty"`
	Kecamatan    *string  `json:"kecamatan,omitempty"`
	TanggalLahir *string  `json:"tanggalLahir,omitempty"`
	JenisKelamin *string  `json:"jenisKelamin,omitempty"`
	Errors       []string `json:"errors,omitempty"`
}

type PlatNomorResult struct {
	Kode     string `json:"kode"`
	Wilayah  string `json:"wilayah"`
	Provinsi string `json:"provinsi"`
}

type Prakiraan struct {
	Waktu          string `json:"waktu"`
	Suhu           string `json:"suhu"`
	Kelembapan     string `json:"kelembapan"`
	Cuaca          string `json:"cuaca"`
	KecepatanAngin string `json:"kecepatanAngin"`
	ArahAngin      string `json:"arahAngin"`
}

type Query struct {
}

type TerbilangResult struct {
	Angka     float64 `json:"angka"`
	Terbilang string  `json:"terbilang"`
}

type WaktuSholatResult struct {
	Kota    string `json:"kota"`
	Tanggal string `json:"tanggal"`
	Subuh   string `json:"subuh"`
	Terbit  string `json:"terbit"`
	Dzuhur  string `json:"dzuhur"`
	Ashar   string `json:"ashar"`
	Maghrib string `json:"maghrib"`
	Isya    string `json:"isya"`
}
