// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bandara struct {
	KodeIata string `json:"kodeIATA"`
	Nama     string `json:"nama"`
	Kota     string `json:"kota"`
	Provinsi string `json:"provinsi"`
}

type CuacaResult struct {
	Provinsi  string       `json:"provinsi"`
	Kota      string       `json:"kota"`
	Prakiraan []*Prakiraan `json:"prakiraan"`
}

type GempaItem struct {
	Tanggal   string `json:"tanggal"`
	Jam       string `json:"jam"`
	Magnitude string `json:"magnitude"`
	Kedalaman string `json:"kedalaman"`
	Lintang   string `json:"lintang"`
	Bujur     string `json:"bujur"`
	Wilayah   string `json:"wilayah"`
	Potensi   string `json:"potensi"`
	Dirasakan string `json:"dirasakan"`
}

type HargaBBMItem struct {
	Nama   string `json:"nama"`
	Harga  int    `json:"harga"`
	Satuan string `json:"satuan"`
	Jenis  string `json:"jenis"`
}

type HargaEmasItem struct {
	Gram         float64 `json:"gram"`
	HargaJual    int     `json:"hargaJual"`
	HargaBuyback int     `json:"hargaBuyback"`
}

type IHSGResult struct {
	Symbol              string  `json:"symbol"`
	Nama                string  `json:"nama"`
	Harga               float64 `json:"harga"`
	Perubahan           float64 `json:"perubahan"`
	PersentasePerubahan float64 `json:"persentasePerubahan"`
	Open                float64 `json:"open"`
	High                float64 `json:"high"`
	Low                 float64 `json:"low"`
	Volume              int     `json:"volume"`
	Waktu               string  `json:"waktu"`
}

type InflasiItem struct {
	Periode        string  `json:"periode"`
	Bulan          string  `json:"bulan"`
	Tahun          int     `json:"tahun"`
	InflasiBulanan float64 `json:"inflasiBulanan"`
	InflasiTahunan float64 `json:"inflasiTahunan"`
	Ihk            float64 `json:"ihk"`
}

type IuranBpjs struct {
	Kelas      string `json:"kelas"`
	Segmen     string `json:"segmen"`
	Nominal    int    `json:"nominal"`
	Keterangan string `json:"keterangan"`
}

type KalenderHijriyahResult struct {
	TanggalMasehi   string `json:"tanggalMasehi"`
	TanggalHijriyah string `json:"tanggalHijriyah"`
	Hari            string `json:"hari"`
	HariArab        string `json:"hariArab"`
	Bulan           string `json:"bulan"`
	BulanArab       string `json:"bulanArab"`
	Tahun           int    `json:"tahun"`
}

type KalenderJawaResult struct {
	TanggalMasehi   string `json:"tanggalMasehi"`
	Hari            string `json:"hari"`
	Pasaran         string `json:"pasaran"`
	Wuku            string `json:"wuku"`
	TahunJawa       int    `json:"tahunJawa"`
	NamaWindu       string `json:"namaWindu"`
	TahunDalamWindu string `json:"tahunDalamWindu"`
}

type KodeBankResult struct {
	Kode string `json:"kode"`
	Nama string `json:"nama"`
}

type KodePosResult struct {
	KodePos   string `json:"kodePos"`
	Kelurahan string `json:"kelurahan"`
	Kecamatan string `json:"kecamatan"`
	Kota      string `json:"kota"`
	Provinsi  string `json:"provinsi"`
}

type KursResult struct {
	MataUang   string  `json:"mataUang"`
	KursBeli   float64 `json:"kursBeli"`
	KursJual   float64 `json:"kursJual"`
	KursTengah float64 `json:"kursTengah"`
	Tanggal    string  `json:"tanggal"`
}

type NIKResult struct {
	Valid        bool     `json:"valid"`
	Nik          string   `json:"nik"`
	Provinsi     *string  `json:"provinsi,omitempty"`
	Kota         *string  `json:"kota,omitempty"`
	Kecamatan    *string  `json:"kecamatan,omitempty"`
	TanggalLahir *string  `json:"tanggalLahir,omitempty"`
	JenisKelamin *string  `json:"jenisKelamin,omitempty"`
	Errors       []string `json:"errors,omitempty"`
}

type PenginapanItem struct {
	ID      string  `json:"id"`
	Nama    string  `json:"nama"`
	Tipe    string  `json:"tipe"`
	Alamat  *string `json:"alamat,omitempty"`
	Bintang *string `json:"bintang,omitempty"`
	Telepon *string `json:"telepon,omitempty"`
	Website *string `json:"website,omitempty"`
	Lat     float64 `json:"lat"`
	Lon     float64 `json:"lon"`
}

type PlatNomorResult struct {
	Kode     string `json:"kode"`
	Wilayah  string `json:"wilayah"`
	Provinsi string `json:"provinsi"`
}

type Prakiraan struct {
	Waktu          string `json:"waktu"`
	Suhu           string `json:"suhu"`
	Kelembapan     string `json:"kelembapan"`
	Cuaca          string `json:"cuaca"`
	KecepatanAngin string `json:"kecepatanAngin"`
	ArahAngin      string `json:"arahAngin"`
}

type Query struct {
}

type SahamResult struct {
	Symbol              string  `json:"symbol"`
	Nama                string  `json:"nama"`
	Harga               float64 `json:"harga"`
	Perubahan           float64 `json:"perubahan"`
	PersentasePerubahan float64 `json:"persentasePerubahan"`
	Open                float64 `json:"open"`
	High                float64 `json:"high"`
	Low                 float64 `json:"low"`
	Volume              int     `json:"volume"`
	Waktu               string  `json:"waktu"`
}

type TerbilangResult struct {
	Angka     float64 `json:"angka"`
	Terbilang string  `json:"terbilang"`
}

type UMRProvinsi struct {
	Provinsi string `json:"provinsi"`
	Kode     string `json:"kode"`
	Upah     int    `json:"upah"`
	Tahun    int    `json:"tahun"`
}

type ValidasiRekeningResult struct {
	Valid      bool   `json:"valid"`
	Bank       string `json:"bank"`
	NoRekening string `json:"noRekening"`
	Panjang    int    `json:"panjang"`
	Keterangan string `json:"keterangan"`
}

type WaktuSholatResult struct {
	Kota    string `json:"kota"`
	Tanggal string `json:"tanggal"`
	Subuh   string `json:"subuh"`
	Terbit  string `json:"terbit"`
	Dzuhur  string `json:"dzuhur"`
	Ashar   string `json:"ashar"`
	Maghrib string `json:"maghrib"`
	Isya    string `json:"isya"`
}
