// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CuacaResult struct {
	Provinsi  string       `json:"provinsi"`
	Kota      string       `json:"kota"`
	Prakiraan []*Prakiraan `json:"prakiraan"`
}

type KalenderJawaResult struct {
	TanggalMasehi   string `json:"tanggalMasehi"`
	Hari            string `json:"hari"`
	Pasaran         string `json:"pasaran"`
	Wuku            string `json:"wuku"`
	TahunJawa       int    `json:"tahunJawa"`
	NamaWindu       string `json:"namaWindu"`
	TahunDalamWindu string `json:"tahunDalamWindu"`
}

type KursResult struct {
	MataUang   string  `json:"mataUang"`
	KursBeli   float64 `json:"kursBeli"`
	KursJual   float64 `json:"kursJual"`
	KursTengah float64 `json:"kursTengah"`
	Tanggal    string  `json:"tanggal"`
}

type NIKResult struct {
	Valid        bool     `json:"valid"`
	Nik          string   `json:"nik"`
	Provinsi     *string  `json:"provinsi,omitempty"`
	Kota         *string  `json:"kota,omitempty"`
	Kecamatan    *string  `json:"kecamatan,omitempty"`
	TanggalLahir *string  `json:"tanggalLahir,omitempty"`
	JenisKelamin *string  `json:"jenisKelamin,omitempty"`
	Errors       []string `json:"errors,omitempty"`
}

type Prakiraan struct {
	Waktu          string `json:"waktu"`
	Suhu           string `json:"suhu"`
	Kelembapan     string `json:"kelembapan"`
	Cuaca          string `json:"cuaca"`
	KecepatanAngin string `json:"kecepatanAngin"`
	ArahAngin      string `json:"arahAngin"`
}

type Query struct {
}

type TerbilangResult struct {
	Angka     float64 `json:"angka"`
	Terbilang string  `json:"terbilang"`
}
